# This spec file was generated by Gideon
# Please report any problem to KDevelop Team <kdevelop-devel@kdevelop.org>
# Thanks to Matthias Saou for his explanations on http://freshrpms.net/docs/fight.html

Name: webcpp
Version: 0.8.2
Release: 0
Vendor: Jeffrey Bakker
Copyright: GNU GPL
Summary: Converts source code into syntax highlighted HTML.
Group: Tools
Packager: Jeffrey Bakker
BuildRoot: %{_tmppath}/%{name}-root
Source: webcpp-0.8.2.tar.gz

%description
Webcpp converts Ada95, Assembler, Basic, C, C#, C++, Cg, CLIPS, Fortran, Haskell, Java, Markup, Modula2, Objective C, Pascal, Perl, PHP, Python, SQL, Tcl, Unix shell, & VHDL into HTML with syntax highlighting and themes.





%prep
%setup
CFLAGS="$RPM_OPT_FLAGS" CXXFLAGS="$RPM_OPT_FLAGS" ./configure \
--target=i386

%build
%configure
make

%install
rm -rf %{buildroot}
%makeinstall

%clean
rm -rf %{buildroot}

%post -p /sbin/ldconfig
%postun -p /sbin/ldconfig
%files
%defattr(-, root, root)
%doc AUTHORS COPYING ChangeLog NEWS README TODO
%{_bindir}/*
%{_libdir}/*.so.*
%{_datadir}/%{name}
%{_mandir}/man8/*
%changelog

