#!/usr/bin/env python

# (g)WebcppUI (C)2005 Jeffrey Bakker
#
# WebcppUI is a Gtk+ interface for Webcpp and MkScs2, providing a unified user
# environment for creating webcpp commands and designing webcpp syntax colour
# schemes.


# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.


import libglade
import gtk

import locale
locale.setlocale(locale.LC_ALL,'')

import os
import re

from random import Random

# WebcppUI class from GladeWrapper =============================================
class webcppwnd(libglade.GladeWrapper):


	# grab widgets from xml ================================================
	def __init__(self, Filename, WindowName, start_dir="."):
		libglade.GladeWrapper.__init__(self, Filename, WindowName)

		self.files_model = gtk.ListStore(str)
		self.tvInputFiles.set_model(self.files_model)
		files_column = gtk.TreeViewColumn("Source Code Files", gtk.CellRendererText(), text=0)
		self.tvInputFiles.append_column(files_column)

		self.set_typical()


	# initialize typical theme =============================================
	def set_typical(self):
		self.ScsFile = ""
		self.c_backgnd.set_color(gtk.gdk.color_parse("#f9f9f9"))
		self.c_preproc.set_color(gtk.gdk.color_parse("#a900a9"))
		self.c_nortext.set_color(gtk.gdk.color_parse("#000000"))
		self.c_symbols.set_color(gtk.gdk.color_parse("#0077dd"))
		self.c_keyword.set_color(gtk.gdk.color_parse("#224fff"))
		self.c_keytype.set_color(gtk.gdk.color_parse("#ff9933"))
		self.c_integer.set_color(gtk.gdk.color_parse("#ff0032"))
		self.c_floatpt.set_color(gtk.gdk.color_parse("#ff23a6"))
		self.c_dblquot.set_color(gtk.gdk.color_parse("#00b800"))
		self.c_sinquot.set_color(gtk.gdk.color_parse("#00b86b"))
		self.c_comment.set_color(gtk.gdk.color_parse("#666666"))


	# new colour scheme ====================================================
	def on_new1_activate(self, widget, data=None):
		self.set_typical()

	def on_tbNew_clicked(self, widget, data=None):
		self.set_typical()


	# set colour from data pair ============================================
	def set_colour_pair(self, element, hexcode):

		if element == "bgcolor" or element == "backgnd":
			self.c_backgnd.set_color(gtk.gdk.color_parse(hexcode))

		else:
			setc = 'self.c_' + element + '.set_color(gtk.gdk.color_parse(hexcode))'
			eval(setc)


	# load colour scheme ===================================================
	def read_scs_data(self):

		chooser = gtk.FileChooserDialog("Input File", None, gtk.FILE_CHOOSER_ACTION_OPEN,
						(gtk.STOCK_CANCEL, gtk.RESPONSE_CANCEL,
						gtk.STOCK_OPEN, gtk.RESPONSE_OK))

		chooser.set_default_response(gtk.RESPONSE_OK)
		filter = gtk.FileFilter()
		filter.set_name("Webcpp Systax Colour Scheme 2 (*.Scs2)")
		filter.add_pattern("*.Scs2")
		chooser.add_filter(filter)

		response = chooser.run()
		if response == gtk.RESPONSE_OK:
			self.ScsFile = chooser.get_filename()
		else:
			chooser.destroy()
			return

		chooser.destroy()

		try:
			file = open(self.ScsFile, "r")
		except IOError:
			print('Cannot open file for reading:'), self.ScsFile
			self.set_typical()
			return

		scs_lines = file.readlines()

		for scsline in scs_lines:

			hexmatch = re.search('>([0-9a-f]{6})</', scsline, re.IGNORECASE)
			tagmatch = re.search('</([a-z]{7})>', scsline, re.IGNORECASE)

			if hexmatch and tagmatch:
				print(tagmatch.group(1), hexmatch.group(1))
				self.set_colour_pair(tagmatch.group(1), '#' + hexmatch.group(1))

		file.close()
		return


	# open scs file ========================================================
	def on_tbOpen_clicked(self, widget, data=None):

		self.read_scs_data()
		return

	def on_open1_activate(self, widget, data=None):

		self.read_scs_data()
		return


	# convert gtk.gdk.Color to hex string ==================================
	def colour_to_hex(self, col):

		return '%02x%02x%02x' % (col.red/256, col.green/256, col.blue/256)


	# write scs data =======================================================
	def write_scs_data(self):
		try:
			file = open(self.ScsFile, "w")
		except IOError:
			print('Cannot open file for writing:', self.ScsFile)
			self.set_typical()
			return

		file.write('<?xml version="1.0"?>\n')
		file.write('<!DOCTYPE SyntaxColourScheme2 SYSTEM "WebcppScheme2.dtd">\n')
		file.write('<SyntaxColourScheme2>\n')

		hexcol = self.colour_to_hex( self.c_backgnd.get_color() )
		file.write('  <bgcolor>' + hexcol + '</bgcolor>\n')

		hexcol = self.colour_to_hex( self.c_preproc.get_color() )
		file.write('  <preproc>' + hexcol + '</preproc>\n')

		hexcol = self.colour_to_hex( self.c_nortext.get_color() )
		file.write('  <nortext>' + hexcol + '</nortext>\n')

		hexcol = self.colour_to_hex( self.c_symbols.get_color() )
		file.write('  <symbols>' + hexcol + '</symbols>\n')

		hexcol = self.colour_to_hex( self.c_keyword.get_color() )
		file.write('  <keyword>' + hexcol + '</keyword>\n')

		hexcol = self.colour_to_hex( self.c_keytype.get_color() )
		file.write('  <keytype>' + hexcol + '</keytype>\n')

		hexcol = self.colour_to_hex( self.c_integer.get_color() )
		file.write('  <integer>' + hexcol + '</integer>\n')

		hexcol = self.colour_to_hex( self.c_floatpt.get_color() )
		file.write('  <floatpt>' + hexcol + '</floatpt>\n')

		hexcol = self.colour_to_hex( self.c_dblquot.get_color() )
		file.write('  <dblquot>' + hexcol + '</dblquot>\n')

		hexcol = self.colour_to_hex( self.c_sinquot.get_color() )
		file.write('  <sinquot>' + hexcol + '</sinquot>\n')

		hexcol = self.colour_to_hex( self.c_comment.get_color() )
		file.write('  <comment>' + hexcol + '</comment>\n')

		file.write('</SyntaxColourScheme2>\n')
		file.close()


	# prompt to save as ====================================================
	def prompt_save_as(self):

		chooser = gtk.FileChooserDialog("Save Colour Scheme", None,
						gtk.FILE_CHOOSER_ACTION_SAVE,
						(gtk.STOCK_CANCEL, gtk.RESPONSE_CANCEL,
						gtk.STOCK_SAVE, gtk.RESPONSE_OK))

		chooser.set_default_response(gtk.RESPONSE_OK)
		filter = gtk.FileFilter()
		filter.set_name("Webcpp Systax Colour Scheme 2 (*.Scs2)")
		filter.add_pattern("*.Scs2")
		chooser.add_filter(filter)

		response = chooser.run()
		if response == gtk.RESPONSE_OK:
			self.ScsFile = chooser.get_filename()

		chooser.destroy()


	# save colour scheme ===================================================
	def on_tbSave_clicked(self, widget, data=None):

		if self.ScsFile == "":
			self.prompt_save_as()

		if self.ScsFile != "":
			self.write_scs_data()
		return

	def on_save1_activate(self, widget, data=None):

		if self.ScsFile == "":
			self.prompt_save_as()

		if self.ScsFile != "":
			self.write_scs_data()
		return


	# save as colour scheme ================================================
	def on_save_as1_activate(self, widget, data=None):

		self.prompt_save_as()
		if self.ScsFile != "":
			self.write_scs_data()
		return


	# create a random colour ===============================================
	def random_color(self):
		Ran = Random()
		Ran.seed()
		rval = Ran.randint(0, 65535)
		gval = Ran.randint(0, 65535)
		bval = Ran.randint(0, 65535)
		color = gtk.gdk.Color(rval, gval, bval)
		return color


	# individual random colours ============================================
	def on_r_backgnd_clicked(self, widget, data=None):
		self.c_backgnd.set_color(self.random_color())

	def on_r_preproc_clicked(self, widget, data=None):
		self.c_preproc.set_color(self.random_color())

	def on_r_nortext_clicked(self, widget, data=None):
		self.c_nortext.set_color(self.random_color())

	def on_r_symbols_clicked(self, widget, data=None):
		self.c_symbols.set_color(self.random_color())

	def on_r_keyword_clicked(self, widget, data=None):
		self.c_keyword.set_color(self.random_color())

	def on_r_keytype_clicked(self, widget, data=None):
		self.c_keytype.set_color(self.random_color())

	def on_r_integer_clicked(self, widget, data=None):
		self.c_integer.set_color(self.random_color())

	def on_r_floatpt_clicked(self, widget, data=None):
		self.c_floatpt.set_color(self.random_color())

	def on_r_dblquot_clicked(self, widget, data=None):
		self.c_dblquot.set_color(self.random_color())

	def on_r_sinquot_clicked(self, widget, data=None):
		self.c_sinquot.set_color(self.random_color())

	def on_r_comment_clicked(self, widget, data=None):
		self.c_comment.set_color(self.random_color())


	# random colour scheme =================================================
	def on_tbRandom_clicked(self, widget, data=None):
		self.ScsFile = ""
		self.c_preproc.set_color(self.random_color())
		self.c_nortext.set_color(self.random_color())
		self.c_symbols.set_color(self.random_color())
		self.c_keyword.set_color(self.random_color())
		self.c_keytype.set_color(self.random_color())
		self.c_integer.set_color(self.random_color())
		self.c_floatpt.set_color(self.random_color())
		self.c_dblquot.set_color(self.random_color())
		self.c_sinquot.set_color(self.random_color())
		self.c_comment.set_color(self.random_color())


	# invert colours =======================================================
	def invert_colour(self, col):

		r = ~col.red
		g = ~col.green
		b = ~col.blue

		inverted = gtk.gdk.Color(r, g, b)
		return inverted

	def on_tbInvert_clicked(self, widget, data=None):

		inverted = self.invert_colour(self.c_backgnd.get_color())
		self.c_backgnd.set_color(inverted)

		inverted = self.invert_colour(self.c_preproc.get_color())
		self.c_preproc.set_color(inverted)

		inverted = self.invert_colour(self.c_nortext.get_color())
		self.c_nortext.set_color(inverted)

		inverted = self.invert_colour(self.c_symbols.get_color())
		self.c_symbols.set_color(inverted)

		inverted = self.invert_colour(self.c_keyword.get_color())
		self.c_keyword.set_color(inverted)

		inverted = self.invert_colour(self.c_keytype.get_color())
		self.c_keytype.set_color(inverted)

		inverted = self.invert_colour(self.c_integer.get_color())
		self.c_integer.set_color(inverted)

		inverted = self.invert_colour(self.c_floatpt.get_color())
		self.c_floatpt.set_color(inverted)

		inverted = self.invert_colour(self.c_dblquot.get_color())
		self.c_dblquot.set_color(inverted)

		inverted = self.invert_colour(self.c_sinquot.get_color())
		self.c_sinquot.set_color(inverted)

		inverted = self.invert_colour(self.c_comment.get_color())
		self.c_comment.set_color(inverted)

	# individual invert colours ============================================
	def on_i_backgnd_clicked(self, widget, data=None):
		self.c_backgnd.set_color(self.invert_colour(self.c_backgnd.get_color()))

	def on_i_preproc_clicked(self, widget, data=None):
		self.c_preproc.set_color(self.invert_colour(self.c_preproc.get_color()))

	def on_i_nortext_clicked(self, widget, data=None):
		self.c_nortext.set_color(self.invert_colour(self.c_nortext.get_color()))

	def on_i_symbols_clicked(self, widget, data=None):
		self.c_symbols.set_color(self.invert_colour(self.c_symbols.get_color()))

	def on_i_keyword_clicked(self, widget, data=None):
		self.c_keyword.set_color(self.invert_colour(self.c_keyword.get_color()))

	def on_i_keytype_clicked(self, widget, data=None):
		self.c_keytype.set_color(self.invert_colour(self.c_keytype.get_color()))

	def on_i_integer_clicked(self, widget, data=None):
		self.c_integer.set_color(self.invert_colour(self.c_integer.get_color()))

	def on_i_floatpt_clicked(self, widget, data=None):
		self.c_floatpt.set_color(self.invert_colour(self.c_floatpt.get_color()))

	def on_i_dblquot_clicked(self, widget, data=None):
		self.c_dblquot.set_color(self.invert_colour(self.c_dblquot.get_color()))

	def on_i_sinquot_clicked(self, widget, data=None):
		self.c_sinquot.set_color(self.invert_colour(self.c_sinquot.get_color()))

	def on_i_comment_clicked(self, widget, data=None):
		self.c_comment.set_color(self.invert_colour(self.c_comment.get_color()))


	def delete_event(self, widget, event, data=None):
		return False


	# exit program =========================================================
	def on_WebcppUI_destroy(self, widget, data=None):
		gtk.main_quit()

	def on_quit1_activate(self, widget, data=None):
		gtk.main_quit()


	# add input file to list ===============================================
	def add_file(self, filename):
		iter = self.files_model.append()
		self.files_model.set(iter,0,filename)


	# create a filechooser for input files =================================
	def on_btnAdd_clicked(self, widget, data=None):
		chooser = gtk.FileChooserDialog("Input File", None, gtk.FILE_CHOOSER_ACTION_OPEN,
						(gtk.STOCK_CANCEL, gtk.RESPONSE_CANCEL,
						gtk.STOCK_OPEN, gtk.RESPONSE_OK))

		chooser.set_default_response(gtk.RESPONSE_OK)
		chooser.set_select_multiple(True)

		filter = gtk.FileFilter()
		filter.set_name("All files")
		filter.add_pattern("*")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Ada95 (*.adb,*.ads,*.ali)")
		filter.add_pattern("*.adb")
		filter.add_pattern("*.ads")
		filter.add_pattern("*.ali")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Assembly (*.asm,*.s)")
		filter.add_pattern("*.asm")
		filter.add_pattern("*.s")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("ASP (*.asp,*.asa)")
		filter.add_pattern("*.asp")
		filter.add_pattern("*.asa")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Basic (*.bas)")
		filter.add_pattern("*.bas")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("C (*.c,*.rc)")
		filter.add_pattern("*.c")
		filter.add_pattern("*.rc")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("C# (*.cs)")
		filter.add_pattern("*.cs")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("C++ (*.cpp,*.cc,*.c++)")
		filter.add_pattern("*.cc")
		filter.add_pattern("*.cpp")
		filter.add_pattern("*.cxx")
		filter.add_pattern("*.c++")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("C/C++ Header (*.h,*.hh,*.hpp)")
		filter.add_pattern("*.h")
		filter.add_pattern("*.hh")
		filter.add_pattern("*.hpp")
		filter.add_pattern("*.hxx")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Objective C (*.m)")
		filter.add_pattern("*.m")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("DOS Batch (*.bat,*.cmd)")
		filter.add_pattern("*.bat")
		filter.add_pattern("*.cmd")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Euphoria (*.e,*.eu,*.ex)")
		filter.add_pattern("*.e")
		filter.add_pattern("*.eu")
		filter.add_pattern("*.ex")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Fortran (*.f,*.f77,*.f90,*.for,*.ftn)")
		filter.add_pattern("*.f")
		filter.add_pattern("*.f77")
		filter.add_pattern("*.f90")
		filter.add_pattern("*.for")
		filter.add_pattern("*.ftn")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Haskell (*.hs,*.lhs)")
		filter.add_pattern("*.hs")
		filter.add_pattern("*.lhs")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Java (*.java)")
		filter.add_pattern("*.java")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("JavaScript (*.js)")
		filter.add_pattern("*.js")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Markup (*.htm,*.html,*.shtml,*.sgml,*.xml)")
		filter.add_pattern("*.htm")
		filter.add_pattern("*.html")
		filter.add_pattern("*.shtml")
		filter.add_pattern("*.sgml")
		filter.add_pattern("*.xml")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("MicroEmacs (*.emf)")
		filter.add_pattern("*.emf")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Modula 2 (*.def,*.mod)")
		filter.add_pattern("*.def")
		filter.add_pattern("*.mod")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("NASA CLIPS (*.clp)")
		filter.add_pattern("*.clp")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("NVidia Cg (*.cg)")
		filter.add_pattern("*.cg")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Pascal (*.pas)")
		filter.add_pattern("*.pas")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Perl (*.cgi,*.pl,*.plx,*.plex,*.pm)")
		filter.add_pattern("*.cgi")
		filter.add_pattern("*.pl")
		filter.add_pattern("*.plx")
		filter.add_pattern("*.plex")
		filter.add_pattern("*.pm")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("PHP (*.php,*.php3,*.inc)")
		filter.add_pattern("*.php")
		filter.add_pattern("*.php3")
		filter.add_pattern("*.inc")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Python (*.py,*.pyw)")
		filter.add_pattern("*.py")
		filter.add_pattern("*.pyw")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("RenderMan (*.rib,*.sl)")
		filter.add_pattern("*.rib")
		filter.add_pattern("*.sl")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Ruby (*.rb)")
		filter.add_pattern("*.rb")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("SQL (*.sql)")
		filter.add_pattern("*.sql")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Tcl (*.tcl,*.tk)")
		filter.add_pattern("*.tcl")
		filter.add_pattern("*.tk")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("Text (*.txt)")
		filter.add_pattern("*.txt")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("UNIX Shell (*.sh)")
		filter.add_pattern("*.sh")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("UnrealScript (*.uc)")
		filter.add_pattern("*.uc")
		chooser.add_filter(filter)

		filter = gtk.FileFilter()
		filter.set_name("VHDL (*.v,*.vhd,*.vhdl)")
		filter.add_pattern("*.v")
		filter.add_pattern("*.vhd")
		filter.add_pattern("*.vhdl")
		chooser.add_filter(filter)

		response = chooser.run()
		if response == gtk.RESPONSE_OK:

			for files in chooser.get_filenames():
				self.add_file(files)

		chooser.destroy()


	# clear input files list ===============================================
	def on_btnEmpty_clicked(self, widget, data=None):
		self.files_model.clear()


	# process input file with webcpp =======================================
	def colour_file(self, model, path, iter, data):

		command = 'webcpp ' + model.get_value(iter, 0) + data
		print(command)
		os.system(command)


	# formulate webcpp options and prepare processing ======================
	def on_btnColour_clicked(self, widget, data=None):
		print('clicked colour')

		options = ' --auto:f'

		if self.entAdvanced.get_text() != "":
			options += ' ' + self.entAdvanced.get_text()

		if self.chkNumbers.get_active():
			print('Show Line Numbers is checked.')
			options += ' -l'

		if self.chkAnchors.get_active():
			print('Make Line Anchors is checked.')
			options += ' -a'

		if self.chkTabSpaces.get_active():
			print('Tabs to Spaces is checked.')
			options += ' -t'

		if self.chkSnippet.get_active():
			print('Snippet Only is checked.')
			options += ' -s'

		if self.chkHyper.get_active():
			print('HyperInclude is checked.')
			options += ' -h'

		if self.chkSuper.get_active():
			print('SuperInclude is checked.')
			options += ' -H'

		if self.chkWebcpp.get_active():
			print('Made with Webcpp is checked.')
			options += ' -m'

		if self.chkExternal.get_active():
			print('External StyleSheet is checked.')
			options += ' -X'

		if self.ScsFile != "":
			options += ' -c=' + self.ScsFile

		self.files_model.foreach(self.colour_file, options)


	# remove file from list ================================================
	def on_btnRemove_clicked(self, widget, data=None):

		sel = self.tvInputFiles.get_selection()
		model, iter = sel.get_selected()
		iter = model.remove(iter)
		return


	# view source code file in editor ======================================
	def on_btnViewSrc_clicked(self, widget, data=None):

		sel = self.tvInputFiles.get_selection()
		model, iter = sel.get_selected()
		file = model.get_value(iter, 0)
		view = 'gedit ' + file + " &"
		os.system(view)
		print(file)
		return


	# view webcpp output file in browser ===================================
	def on_btnViewHtm_clicked(self, widget, data=None):

		sel = self.tvInputFiles.get_selection()
		model, iter = sel.get_selected()
		file = model.get_value(iter, 0)
		view = 'mozilla ' + file + ".html &"
		os.system(view)
		print(file)
		return


	# webcpp menu items ====================================================
	def on_colourize1_activate(self, widget, data=None):
		self.on_btnColour_clicked(widget)

	def on_source_code1_activate(self, widget, data=None):
		self.on_btnViewSrc_clicked(widget)

	def on_html_output1_activate(self, widget, data=None):
		self.on_btnViewHtm_clicked(widget)


	# about webcppui =======================================================
	def goto_url(self, dialog, website, data=None):
		visit = 'mozilla ' + website + ' &'
		os.system(visit)

	def on_tbAbout_clicked(self, widget, data=None):

		try:
			file = open("COPYING", "r")
		except IOError:
			print('Cannot open license file for reading')
			license = "GNU General Public License (GPL)"

		license = file.read()
		authors = ["Webcpp & WebcppUI by Jeffrey Bakker", "GladeWrapper by Padraig Brady"]

		about = gtk.AboutDialog()

		gtk.about_dialog_set_url_hook(self.goto_url, "http://webcpp.sourceforge.net")

		about.set_name("(g)WebcppUI")
		about.set_version("2.0.1")
		about.set_copyright("(C)2006 Jeffrey Bakker")
		about.set_authors(authors)
		about.set_license(license)
		about.set_website("http://webcpp.sourceforge.net")
		about.set_website_label("http://webcpp.sf.net")

		about.run()
		about.destroy()

	def on_about1_activate(self, widget, data=None):
		self.on_tbAbout_clicked(widget)


# start the application ========================================================
WebcppUI = webcppwnd("./webcppui.glade", "WebcppUI")

gtk.main()
# end of program ===============================================================
