// The RenderMan Shading Language Language definition file for Web C Plus Plus
// Generated by Mark Williams <markdjwilliams@hotmail.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langrenderman.h"

LangRenderMan ::LangRenderMan() {

	fill();
	init_switches();

	doCaseKeys = No;
	doPreProc  = Yes;
	doCinComnt = Yes;
	doBigComnt = Yes;
	doUnxComnt = Yes;
}

void LangRenderMan ::fill() {

	string K[] = {
"break",
"color",
"continue",
"displacement",
"else",
"environment",
"extern",
"float",
"for",
"if",
"illuminance",
"illuminate",
"imager",
"light",
"matrix",
"normal",
"output",
"point",
"return",
"shadow",
"solar",
"string",
"surface",
"texture",
"transformation",
"uniform",
"varying",
"vector",
"vertex",
"void",
"volume",
"while"
	};
	for(int k=0;k < 32;k++) {keys.push_back(K[k]);}
}
