// The Euphoria Language definition file for Web C Plus Plus
// Generated by George Lewis <ghlewis@hotmail.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#include "langeuphoria.h"

#include <algorithm>
#include <iterator>

LangEuphoria ::LangEuphoria() {

    fill();
    init_switches();

    doStringsSinQuote = true;
    doUnderscoreNumbers = Yes;
    doAdaComnt = Yes;
}

void LangEuphoria ::fill() {

    string K[] = {"and",       "break",        "by",       "case",   "constant",
                  "continue",  "do",           "else",     "elsif",  "elsifdef",
                  "elsedef",   "end",          "endif",    "enum",   "exit",
                  "export",    "fall_through", "fallthru", "for",    "function",
                  "global",    "goto",         "if",       "ifdef",  "include",
                  "label",     "namespace",    "not",      "or",     "override",
                  "procedure", "public",       "return",   "switch", "then",
                  "to",        "type",         "while",    "with",   "without",
                  "xor"};
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // Euphoria built-in types
    string T[] = {"atom", "integer", "object", "sequence"};
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
