// The SQL Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langsql.h"

LangSQL ::LangSQL() {

	fill();
	init_switches();

	doCaseKeys  = No;
	doRemComnt  = Yes;
	doAdaComnt  = Yes;
	doBigComnt  = Yes;
}

void LangSQL ::fill() {

	string K[] = {
    "*","ALTER","AND","AS","AVERAGE","BEGIN","BY","CLOSE","COMMIT","COUNT",
    "CREATE","CURSOR","DATABASE","DEALLOCATE","DECLARE","DIVIDE","DROP",
    "EXECUTE","FETCH","FROM","FULL","GRANT","GROUP","HAVING","INDEX","INNER",
    "INTERSECT","IS","LEFT","MAXIMUM","MINIMUM","NOT","NULL","ON","OR","ORDER",
    "OUTER","PROCEDURE","REVOKE","RIGHT","ROLLBACK","SELECT","SET","SUM",
    "TABLE","TRANSACTION","TRIGGER","UNION","USER","VIEW","WHERE"
	};
	for(int k=0;k < 51;k++) {keys.push_back(K[k]);}
}
