// The Basic Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_Basic
#define LANG_DEF_Basic

#include "lang_rules.h"

class LangBasic : public LanguageRules {

  public:
    LangBasic();
    void initReservedWords() override;
};

#endif // LANG_DEF_Basic
