// The Ruby Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker <jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langruby.h"

LangRuby ::LangRuby() {

	fill();
	init_switches();


	doScalars  = Yes;
	doArrays   = Yes;
	doHashes   = Yes;
	doUnxComnt = Yes;
}

void LangRuby ::fill() {

	string K[] = {
"BEGIN",
"END",
"alias",
"and",
"begin",
"break",
"case",
"class",
"def",
"defined",
"do",
"else",
"elsif",
"end",
"ensure",
"false",
"for",
"if",
"in",
"module",
"next",
"nil",
"not",
"or",
"redo",
"rescue",
"retry",
"return",
"self",
"super",
"then",
"true",
"undef",
"unless",
"until",
"when",
"while",
"yield",
	};
	for(int k=0;k < 38;k++) {keys.push_back(K[k]);}
}

