
// The Euphoria Language definition file for Web C Plus Plus
// Generated by George Lewis <ghlewis@hotmail.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_EUPHORIA
#define LANG_DEF_EUPHORIA

#include "engine.h"

class LangEuphoria : public Engine {

  public:
    LangEuphoria();
    void fill() override;
};

#endif // LANG_DEF_EUPHORIA
