// The Haskell Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_Haskell
#define LANG_DEF_Haskell

#include "engine.h"

class LangHaskell : public Engine {

 public:
	LangHaskell();
	~LangHaskell() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_Haskell

