// The ObjectiveC Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_ObjectiveC
#define LANG_DEF_ObjectiveC

#include "langc.h"

class LangObjectiveC : public virtual LangC {

 public:
	LangObjectiveC();
	virtual ~LangObjectiveC() {IO->close();}
    void fill() override;

};

#endif //LANG_DEF_ObjectiveC
