// The Pascal Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for modern Object Pascal (Free Pascal / Delphi)

#include "langpascal.h"

#include <algorithm>
#include <iterator>
#include <string>

using std::string;

LangPascal::LangPascal() {

    initReservedWords();

    doStringsDblQuote = false;
    doStringsSinQuote = true;
    doCaseKeys = false;
    doHashes = true;
    doPasComnt = true;
    doCinComnt = true;
    doUnderscoreNumbers = true;
}

void LangPascal::initReservedWords() {

    // Object Pascal keywords (Free Pascal 3.2 / Delphi 12)
    string K[] = {
        "absolute",
        "abstract",
        "and",
        "as",
        "asm",
        "assembler",
        "begin",
        "break",
        "case",
        "class",
        "const",
        "constructor",
        "continue",
        "default",
        "destructor",
        "dispinterface",
        "div",
        "do",
        "downto",
        "else",
        "end",
        "except",
        "export",
        "exports",
        "external",
        "false",
        "file",
        "final",
        "finalization",
        "finally",
        "for",
        "forward",
        "function",
        "generic",
        "goto",
        "if",
        "implementation",
        "implements",
        "in",
        "inherited",
        "initialization",
        "inline",
        "interface",
        "is",
        "label",
        "library",
        "message",
        "mod",
        "new",
        "nil",
        "not",
        "of",
        "on",
        "operator",
        "or",
        "otherwise",
        "out",
        "overload",
        "override",
        "packed",
        "private",
        "procedure",
        "program",
        "property",
        "protected",
        "public",
        "published",
        "raise",
        "read",
        "readln",
        "record",
        "reintroduce",
        "repeat",
        "resourcestring",
        "sealed",
        "self",
        "set",
        "shl",
        "shr",
        "specialize",
        "static",
        "strict",
        "then",
        "threadvar",
        "to",
        "true",
        "try",
        "type",
        "unit",
        "until",
        "uses",
        "var",
        "virtual",
        "while",
        "with",
        "write",
        "writeln",
        "xor",
    };
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // Object Pascal types (Free Pascal 3.2 / Delphi 12)
    string T[] = {
        "AnsiChar", "AnsiString", "Boolean",     "Byte",       "ByteBool",
        "Cardinal", "Char",       "Comp",        "Currency",   "Double",
        "DWord",    "Extended",   "Int64",       "Integer",    "LongBool",
        "LongInt",  "LongWord",   "NativeInt",   "NativeUInt", "PAnsiChar",
        "PChar",    "Pointer",    "PWideChar",   "QWord",      "Real",
        "Real48",   "ShortInt",   "ShortString", "Single",     "SizeInt",
        "SizeUInt", "SmallInt",   "String",      "UInt64",     "UnicodeString",
        "Variant",  "WideChar",   "WideString",  "Word",       "WordBool",
        "array",    "boolean",    "byte",        "char",       "double",
        "extended", "integer",    "longint",     "object",     "real",
        "string",   "word",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
