// The VHDL Language definition file for Web C Plus Plus
// Generated by Thomas Hedler<thomas.hedler@fen-net.de> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for VHDL-2019 (IEEE 1076-2019)

#ifndef LANG_DEF_VHDL
#define LANG_DEF_VHDL

#include "lang_rules.h"

class LangVHDL : public LanguageRules {

  public:
    LangVHDL();
    void initReservedWords() override;
};

#endif // LANG_DEF_VHDL
