// The Euphoria Language definition file for Web C Plus Plus
// Generated by George Lewis <ghlewis@hotmail.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langeuphoria.h"

LangEuphoria ::LangEuphoria() {

	fill();
	init_switches();


	doAdaComnt  = Yes;
}

void LangEuphoria ::fill() {

	string K[] = {
  "by","constant","do","else","elsif","end","exit","for","function","global",
  "if","include","not","or","procedure","return","then","to","type","while",
  "with","without","xor","and"
	};

	for(int k=0;k < 24;k++) {keys.push_back(K[k]);}
}
