// The Fortran Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langfortran.h"

LangFortran ::LangFortran() {

	fill();
	init_switches();

	doCaseKeys = No;
	doPreProc  = Yes;
	doFtnComnt = Yes;
}

void LangFortran ::fill() {

	string K[] = {
		"ACCEPT","ASSIGN","AUTOMATIC","Assignment","BACKSPACE","BLOCK",
		"BYTECALL","CLOSE","COMMON","CONTINUE","DATA","DECODE",
		"DIMENSION","DO","ELSE","ENCODE","END","ENDIF","ENTRY",
		"EQUIVALENCE","EXTERNAL","FILE","FORMAT","FUNCTION","GO","IF",
		"IMPLICIT","INCLUDE","INQUIRE","INTRINSIC","MAP","NAMELIST",
		"OPEN","OPTIONS","PARAMETER","PAUSE","POINTER","PRINT",
		"PROGRAM","READ","RECORD","RETURN","REWIND","SAVE","STATIC",
		"STOP","STRUCTURE","SUBROUTINE","THEN","TO","TYPE","UNION",
		"UNTIL","VIRTUAL","WHILE","WRITE"
	};
	for(int k=0;k < 56;k++) {keys.push_back(K[k]);}

	string T[] = {
		"BYTE","CHARACTER","COMPLEX","DOUBLE","INTEGER","LOGICAL",
		"REAL","PRECISION","VOLATILE"
	};
	for(int t=0;t < 9;t++) {types.push_back(T[t]);}
}

