// The Modula2 Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langmodula.h"

LangModula2 ::LangModula2() {

	fill();
	init_switches();

	doPasComnt = Yes;
}

void LangModula2 ::fill() {

	string K[] = {
		"AND","BEGIN","BY","CASE","CONST","DEFINITION","DIV",
		"DO","ELSE","ELSIF","END","EXIT","EXPORT","FALSE","FOR","FROM",
		"IF","IMPLEMENTATION","IMPORT","IN","LOOP","MOD","MODULE",
		"NOT","OF","OR","POINTER","PROCEDURE","QUALIFIED","REPEAT",
		"RETURN","SET","THEN","TO","TRUE","TYPE","UNTIL","VAR","WHILE",
		"WITH"
	};
	for(int k=0;k < 40;k++) {keys.push_back(K[k]);}

	string T[] = {
		"ACHAR","ARRAY","BITSET","BOOLEAN","CARDINAL","CHAR","INTEGER",
		"LONGCARD","LONGCOMPLEX","LONGINT","LONGREAL","REAL","RECORD",
		"SHORTCARD","SHORTINT","UCHAR"
	};
	for(int t=0;t < 16;t++) {types.push_back(T[t]);}
}
