// The Fortran Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for modern Fortran (Fortran 2023)

#include "langfortran.h"

#include <algorithm>
#include <iterator>

LangFortran ::LangFortran() {

    fill();
    init_switches();

    doStringsSinQuote = true;
    doCaseKeys = No;
    doPreProc = Yes;
    doFtnComnt = Yes;
    doBigComnt = Yes;
}

void LangFortran ::fill() {

    // Fortran keywords (FORTRAN 77 through Fortran 2023)
    string K[] = {
        "ABSTRACT",     "ACCEPT",      "ALLOCATABLE",
        "ALLOCATE",     "ASSIGN",      "ASSOCIATE",
        "ASYNCHRONOUS", "AUTOMATIC",   "BACKSPACE",
        "BIND",         "BLOCK",       "CALL",
        "CASE",         "CHANGE",      "CLASS",
        "CLOSE",        "CODIMENSION", "COMMON",
        "CONCURRENT",   "CONTAINS",    "CONTIGUOUS",
        "CONTINUE",     "CRITICAL",    "CYCLE",
        "DATA",         "DEALLOCATE",  "DEFAULT",
        "DEFERRED",     "DIMENSION",   "DO",
        "ELEMENTAL",    "ELSE",        "ELSEWHERE",
        "END",          "ENDFILE",     "ENDIF",
        "ENTRY",        "ENUM",        "ENUMERATOR",
        "EQUIVALENCE",  "ERROR",       "EXIT",
        "EXTENDS",      "EXTERNAL",    "FILE",
        "FINAL",        "FLUSH",       "FORALL",
        "FORMAT",       "FUNCTION",    "GENERIC",
        "GO",           "IF",          "IMAGES",
        "IMPLICIT",     "IMPORT",      "IMPURE",
        "INCLUDE",      "INQUIRE",     "INTENT",
        "INTERFACE",    "INTRINSIC",   "LOCK",
        "MODULE",       "NAMELIST",    "NON_OVERRIDABLE",
        "NONE",         "NOPASS",      "NULLIFY",
        "ONLY",         "OPEN",        "OPTIONAL",
        "OPTIONS",      "PARAMETER",   "PASS",
        "PAUSE",        "POINTER",     "PRINT",
        "PRIVATE",      "PROCEDURE",   "PROGRAM",
        "PROTECTED",    "PUBLIC",      "PURE",
        "READ",         "RECURSIVE",   "RESULT",
        "RETURN",       "REWIND",      "SAVE",
        "SELECT",       "SEQUENCE",    "STATIC",
        "STOP",         "STRUCTURE",   "SUBMODULE",
        "SUBROUTINE",   "SYNC",        "TARGET",
        "TEAM",         "THEN",        "TO",
        "TYPE",         "UNLOCK",      "USE",
        "VALUE",        "VOLATILE",    "WAIT",
        "WHERE",        "WHILE",       "WRITE",
    };
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // Fortran types (FORTRAN 77 through Fortran 2023)
    string T[] = {
        "BYTE",    "CHARACTER", "COMPLEX",   "DOUBLE",
        "INTEGER", "LOGICAL",   "PRECISION", "REAL",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
