// The Fortran Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_Fortran
#define LANG_DEF_Fortran

#include "engine.h"

class LangFortran : public Engine {

  public:
    LangFortran();
    void fill() override;
};

#endif // LANG_DEF_Fortran
