// The Pascal Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langpascal.h"

LangPascal ::LangPascal() {

	fill();
	init_switches();

	doCaseKeys = No;
	doHashes   = Yes;
	doPasComnt = Yes;
}

void LangPascal ::fill() {

	string K[] = {
		"abs","and","arctan","begin","case","const","cos","dispose",
		"div","do","downto","else","end","eof","eoln","exp","false",
		"file","for","forward","function","goto","if","in","input",
		"label","ln","maxint","mod","new","nil","not","odd","of","or",
		"ord","output","pack","packed","page","pred","procedure",
		"program","read","readln","repeat","reset","rewrite","round",
		"set","sin","sqr","sqrt","succ","text","then","to","true",
		"trunc","type","until","var","while","with","write","writeln"
	};
	for(int k=0;k < 66;k++) {keys.push_back(K[k]);}

	string T[] = {
		"array","boolean","byte","char","double","extended","integer",
		"longint","real","record","string","word"
	};
	for(int t=0;t < 12;t++) {types.push_back(T[t]);}
}
