// The Fortran Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_Fortran
#define LANG_DEF_Fortran

#include "engine.h"

class LangFortran : public Engine {

 public:
	LangFortran();
	~LangFortran() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_Fortran
