// The Basic Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langbasic.h"

#include <algorithm>
#include <iterator>
#include <string>

using std::string;

LangBasic ::LangBasic() {

    initReservedWords();

    doCaseKeys = false;
    doLabels = true;
    doAsmComnt = true;
    doRemComnt = true;
}

void LangBasic ::initReservedWords() {

    string K[] = {
        "ABS",   "AND",   "ASC",     "BYE",    "CHR",  "CLS",   "DATA",  "DEL",
        "DIM",   "END",   "FOR",     "GOSUB",  "GOTO", "IF",    "INPUT", "LEN",
        "LET",   "LIST",  "LOAD",    "LOCATE", "LOG",  "MERGE", "MID",   "MOD",
        "NEW",   "NEXT",  "NOT",     "ON",     "OR",   "POKE",  "PRINT", "RAND",
        "READ",  "RENUM", "RESTORE", "RETURN", "RND",  "RUN",   "SAVE",  "SGN",
        "SIN",   "SQR",   "SQRT",    "STOP",   "STR",  "TO",    "VAL",   "WEND",
        "WHILE", "XOR"};
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));
}
