// The Tcl Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langtcl.h"

LangTcl ::LangTcl() {

	fill();
	init_switches();


	doScalars  = Yes;
//	doTclComnt = Yes;
	doUnxComnt = Yes;
}

void LangTcl ::fill() {

	string K[] = {
  "append","array","break","case","catch","cd","close","concat","continue",
  "eof","error","eval","exec","exit","expr","file","flush","for","foreach",
  "format","gets","glob","global","history","if","incr","info","join",
  "lappened","lindex","linsert","list","llength","lrange","lreplace","lsearch",
  "lsort","open","pid","proc","puts","pwd","read","regexp","regsub","rename",
  "return","scan","seek","set","source","split","string","switch","tell",
  "time","trace","unknown","unset","uplevel","upvar","while"
	};
	for(int k=0;k < 62;k++) {keys.push_back(K[k]);}
}
