
// The Power Builder 6.x Language definition file for Web C Plus Plus
// Generated by Philippe Torche<philippe.torche@swissonline.ch> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_POWER_BUILDER
#define LANG_DEF_POWER_BUILDER

#include "engine.h"

class LangPBuilder : public Engine {

 public:
	LangPBuilder();
	~LangPBuilder() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_POWER_BUILDER
