// The Ada Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for Ada 2022 (ISO/IEC 8652:2023)

#include "langada.h"

#include <algorithm>
#include <iterator>

LangAda ::LangAda() {

    fill();
    init_switches();

    // Ada uses ' for both character literals ('x') and attribute access
    // (Integer'Range, T'First), which the engine cannot distinguish.
    // Single-quote string highlighting is therefore disabled.
    doStringsSinQuote = false;
    doCaseKeys = No; // Ada is case-insensitive
    doLabels = Yes;
    doAdaComnt = Yes; // -- line comments
    doSymbols = Yes;
}

void LangAda ::fill() {

    // Ada 2022 reserved words (Ada 95 + Ada 2005 + Ada 2012 + Ada 2022)
    string K[] = {
        "abort",     "abs",       "abstract",     "accept",     "access",
        "aliased",   "all",       "and",          "array",      "at",
        "begin",     "body",      "case",         "constant",   "declare",
        "delay",     "delta",     "digits",       "do",         "else",
        "elsif",     "end",       "entry",        "exception",  "exit",
        "for",       "function",  "generic",      "goto",       "if",
        "in",        "interface", "is",           "limited",    "loop",
        "mod",       "new",       "not",          "null",       "of",
        "or",        "others",    "out",          "overriding", "package",
        "parallel",  "pragma",    "private",      "procedure",  "protected",
        "raise",     "range",     "record",       "rem",        "renames",
        "requeue",   "return",    "reverse",      "select",     "separate",
        "some",      "subtype",   "synchronized", "tagged",     "task",
        "terminate", "then",      "type",         "until",      "use",
        "when",      "while",     "with",         "xor",
    };
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // Ada predefined types, subtypes, and common library types
    string T[] = {
        "Address",
        "Boolean",
        "Bounded_String",
        "Character",
        "Count",
        "Duration",
        "Exception_Id",
        "Exception_Occurrence",
        "File_Type",
        "Float",
        "Integer",
        "Long_Float",
        "Long_Integer",
        "Long_Long_Float",
        "Long_Long_Integer",
        "Natural",
        "Positive",
        "Short_Float",
        "Short_Integer",
        "Short_Short_Integer",
        "Storage_Element",
        "String",
        "Suspension_Object",
        "Tag",
        "Task_Id",
        "Time",
        "Time_Span",
        "Unbounded_String",
        "Wide_Character",
        "Wide_String",
        "Wide_Wide_Character",
        "Wide_Wide_String",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
