// The Ada95 Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langada.h"

LangAda95 ::LangAda95() {

	fill();
	init_switches();

	doLabels   = Yes;
	doAdaComnt = Yes;
}

void LangAda95 ::fill() {

	string K[] = {
	"abort","abs","abstract","accept","access","aliased","all","and","array",
	"at","begin","body","case","constant","declare","delay","delta","digits",
	"do","else","elsif","end","entry","exception","exit","for","function",
	"generic","goto","if","in","is","limited","loop","mod","new","not","null",
	"of","or","others","out","package","pragma","private","procedure",
	"protected","raise","range","record","rem","renames","requeue","return",
	"reverse","select","separate","subtype","tagged","task","terminate",
	"then","type","until","use","when","while","with","xor"
	};
	for(int k=0;k < 69;k++) {keys.push_back(K[k]);}
}
