// The VHDL Language definition file for Web C Plus Plus
// Generated by Thomas Hedler<thomas.hedler@fen-net.de> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for VHDL-2019 (IEEE 1076-2019)

// Very High Speed Integrated Circuit Hardware Description Language

#include "langvhdl.h"

#include <algorithm>
#include <iterator>
#include <string>

using std::string;

LangVHDL::LangVHDL() {

    initReservedWords();

    doStringsSinQuote = true;
    doCaseKeys = false; // VHDL is case-insensitive
    doLabels = true;
    doInlineCommentDblDash = true; // -- line comments
    doSymbols = true;
    doUnderscoreNumbers = true;
}

void LangVHDL::initReservedWords() {

    // VHDL-2019 reserved words (IEEE 1076-2019)
    string K[] = {
        "ABS",     "ACCESS",       "AFTER",         "ALIAS",      "ALL",
        "AND",     "ARCHITECTURE", "ARRAY",         "ASSERT",     "ATTRIBUTE",
        "BEGIN",   "BLOCK",        "BODY",          "BUFFER",     "BUS",
        "CASE",    "COMPONENT",    "CONFIGURATION", "CONSTANT",   "CONTEXT",
        "DEFAULT", "DISCONNECT",   "DOWNTO",        "ELSE",       "ELSIF",
        "END",     "ENTITY",       "EXIT",          "FILE",       "FOR",
        "FORCE",   "FUNCTION",     "GENERATE",      "GENERIC",    "GROUP",
        "GUARDED", "IF",           "IMPURE",        "IN",         "INERTIAL",
        "INOUT",   "IS",           "LABEL",         "LIBRARY",    "LINKAGE",
        "LITERAL", "LOOP",         "MAP",           "MOD",        "NAND",
        "NEW",     "NEXT",         "NOR",           "NOT",        "NULL",
        "OF",      "ON",           "OPEN",          "OR",         "OTHERS",
        "OUT",     "PACKAGE",      "PARAMETER",     "PORT",       "POSTPONED",
        "PRIVATE", "PROCEDURE",    "PROCESS",       "PROTECTED",  "PURE",
        "RANGE",   "RECORD",       "REGISTER",      "REJECT",     "RELEASE",
        "REM",     "REPORT",       "RETURN",        "ROL",        "ROR",
        "SELECT",  "SEVERITY",     "SIGNAL",        "SHARED",     "SLA",
        "SLL",     "SRA",          "SRL",           "SUBTYPE",    "THEN",
        "TO",      "TRANSPORT",    "TYPE",          "UNAFFECTED", "UNITS",
        "UNTIL",   "USE",          "VARIABLE",      "VIEW",       "WAIT",
        "WHEN",    "WHILE",        "WITH",          "XNOR",       "XOR",
    };
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // VHDL predefined types from package std.standard and ieee libraries
    string T[] = {
        "BIT",
        "BIT_VECTOR",
        "BOOLEAN",
        "BOOLEAN_VECTOR",
        "CHARACTER",
        "DELAY_LENGTH",
        "FILE_OPEN_KIND",
        "FILE_OPEN_STATUS",
        "INTEGER",
        "INTEGER_VECTOR",
        "NATURAL",
        "POSITIVE",
        "REAL",
        "REAL_VECTOR",
        "SEVERITY_LEVEL",
        "SIGNED",
        "STD_LOGIC",
        "STD_LOGIC_VECTOR",
        "STD_ULOGIC",
        "STD_ULOGIC_VECTOR",
        "STRING",
        "TEXT",
        "TIME",
        "TIME_VECTOR",
        "UNSIGNED",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
