// The SQL Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_SQL
#define LANG_DEF_SQL

#include "engine.h"

class LangSQL : public Engine {

 public:
	LangSQL();
	~LangSQL() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_SQL
