// The RenderMan Shading Language definition file for Web C Plus Plus
// Generated by Mark Williams <markdjwilliams@hotmail.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for RenderMan RSL and Open Shading Language (OSL)

#include "langrenderman.h"

#include <algorithm>
#include <iterator>
#include <string>

using std::string;

LangRenderMan::LangRenderMan() {

    initReservedWords();

    doPreProc = true;  // #include, #define
    doInlineCommentDblSlash = true; // // line comments
    doBlockCommentPLI = true; // /* */ block comments
    doSymbols = true;
}

void LangRenderMan::initReservedWords() {

    // RSL and OSL keywords (combined for .sl file compatibility)
    string K[] = {
        "and",          "break",      "closure", "continue",
        "displacement", "do",         "else",    "emit",
        "environment",  "extern",     "for",     "if",
        "illuminance",  "illuminate", "imager",  "light",
        "not",          "or",         "output",  "public",
        "return",       "shader",     "shadow",  "solar",
        "struct",       "surface",    "texture", "transformation",
        "uniform",      "varying",    "vertex",  "void",
        "volume",       "while",
    };
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // RSL and OSL data types
    string T[] = {
        "color",  "float", "int",    "matrix",
        "normal", "point", "string", "vector",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
