
// The emf Language definition file for Web C Plus Plus
// Generated by Dr. Detlef Groth<dgroth@gmx.de> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_EMF
#define LANG_DEF_EMF

#include "engine.h"

class LangEmf : public Engine {

 public:
	LangEmf();
	~LangEmf() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_EMF
