// The Modula2 Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_Modula2
#define LANG_DEF_Modula2

#include "engine.h"

class LangModula2 : public Engine {

 public:
	LangModula2();
	~LangModula2() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_Modula2
