// The SQL Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_SQL
#define LANG_DEF_SQL

#include "lang_rules.h"

class LangSQL : public LanguageRules {

  public:
    LangSQL();
    void initReservedWords() override;
};

#endif // LANG_DEF_SQL
