// The DOS Batch Language definition file for Web C Plus Plus
// Generated by Daniel Lin <dan@dlin.d2g.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_BATCH
#define LANG_DEF_BATCH

#include "lang_rules.h"

class LangBatch : public LanguageRules {

  public:
    LangBatch();
    void initReservedWords() override;
};

#endif // LANG_DEF_BATCH
