// The Cg Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langcg.h"

LangCg ::LangCg() {

	fill();
	init_switches();

	doSymbols   = Yes;
	doPreProc   = Yes;
	doCinComnt  = Yes;
	doBigComnt  = Yes;
}

void LangCg ::fill() {

	string K[] = {
"break",
"case",
"const",
"continue",
"default",
"discard",
"do",
"else",
"enum",
"extern",
"false",
"for",
"function",
"goto",
"if",
"return",
"struct",
"switch",
"true",
"typedef",
"uniform",
"while"
	};
	for(int k=0;k < 22;k++) {keys.push_back(K[k]);}

	string T[] = {
"bool",
"float4x4",
"float4",
"float3x3",
"float3",
"float2x2",
"float2",
"float",
"in",
"inout",
"int",
"out",
"static",
"void",
"volatile",
	};
	for(int t=0;t < 15;t++) {types.push_back(T[t]);}
}
