// The Basic Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_Basic
#define LANG_DEF_Basic

#include "engine.h"

class LangBasic : public Engine {

  public:
    LangBasic();
    void fill() override;
};

#endif // LANG_DEF_Basic
