// The JavaScript Language definition file for Web C Plus Plus
// Generated by forrest johnston<forrest.johnston@attbi.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for modern JavaScript (ES2025)

#include "langjscript.h"

#include <algorithm>
#include <iterator>

LangJScript ::LangJScript() {

    fill();
    init_switches();

    doStringsSinQuote = true;
    doStringsBackTick = true;
    doSymbols = Yes;
    doCinComnt = Yes;
    doBigComnt = Yes;
    // JavaScript template literal interpolation: `text ${expr}`
    doInterpolate = true;
    interpolStart = "${";
    interpolEnd = '}';
    interpolCssClass = "preproc"; // backtick strings use preproc class
}

void LangJScript ::fill() {

    // JavaScript keywords (ES2025)
    string K[] = {
        "as",     "async",      "await",    "break",    "case",      "catch",
        "class",  "const",      "continue", "debugger", "default",   "delete",
        "do",     "else",       "export",   "extends",  "false",     "finally",
        "for",    "from",       "function", "get",      "if",        "import",
        "in",     "instanceof", "let",      "new",      "null",      "of",
        "return", "set",        "static",   "super",    "switch",    "this",
        "throw",  "true",       "try",      "typeof",   "undefined", "var",
        "void",   "while",      "with",     "yield",
    };
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // JavaScript built-in types and globals (ES2025)
    string T[] = {
        "Array",
        "ArrayBuffer",
        "BigInt",
        "Boolean",
        "DataView",
        "Date",
        "Error",
        "Float32Array",
        "Float64Array",
        "Function",
        "Generator",
        "Int8Array",
        "Int16Array",
        "Int32Array",
        "Intl",
        "Iterator",
        "JSON",
        "Map",
        "Math",
        "Number",
        "Object",
        "Promise",
        "Proxy",
        "RangeError",
        "ReferenceError",
        "Reflect",
        "RegExp",
        "Set",
        "SharedArrayBuffer",
        "String",
        "Symbol",
        "SyntaxError",
        "TypeError",
        "Uint8Array",
        "Uint16Array",
        "Uint32Array",
        "WeakMap",
        "WeakRef",
        "WeakSet",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
