// The Modula2 Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_Modula2
#define LANG_DEF_Modula2

#include "engine.h"

class LangModula2 : public Engine {

  public:
    LangModula2();
    ~LangModula2() { IO->close(); }
    virtual void fill();
};

#endif // LANG_DEF_Modula2
