// The Tcl Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_Tcl
#define LANG_DEF_Tcl

#include "lang_rules.h"

class LangTcl : public LanguageRules {

  public:
    LangTcl();
    void initReservedWords() override;
};

#endif // LANG_DEF_Tcl
