// The Cg Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#include "langcg.h"

#include <algorithm>
#include <iterator>
#include <string>

using std::string;

LangCg ::LangCg() {

    initReservedWords();

    doStringsSinQuote = true;
    doSymbols = true;
    doPreProc = true;
    doInlineCommentDblSlash = true;
    doBlockCommentPLI = true;
}

void LangCg ::initReservedWords() {

    string K[] = {"break",   "case",   "const",    "continue", "default",
                  "discard", "do",     "else",     "enum",     "extern",
                  "false",   "for",    "function", "goto",     "if",
                  "return",  "struct", "switch",   "true",     "typedef",
                  "uniform", "while"};
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    string T[] = {
        "bool",     "float4x4", "float4", "float3x3", "float3",
        "float2x2", "float2",   "float",  "in",       "inout",
        "int",      "out",      "static", "void",     "volatile",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
