
// The Cg Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_NVIDIA_CG_SHADING_LANGUAGE
#define LANG_DEF_NVIDIA_CG_SHADING_LANGUAGE

#include "engine.h"

class LangCg : public Engine {

 public:
	LangCg();
	~LangCg() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_NVIDIA_CG_SHADING_LANGUAGE
