// The VHDL Language definition file for Web C Plus Plus
// Generated by Thomas Hedler<thomas.hedler@fen-net.de> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

// Very High Speed Integrated Circuit Hardware Description Language

#include "langvhdl.h"

LangVHDL ::LangVHDL() {

	fill();
	init_switches();


	doCaseKeys  = No;
	doLabels    = Yes;
	doAdaComnt  = Yes;
}

void LangVHDL ::fill() {
	string K[] = {
    "ABS","ACCESS","AFTER","ALIAS","ALL","AND","ARCHITECTURE","ARRAY","ASSERT",
    "ATTRIBUTE","BEGIN","BLOCK","BODY","BUFFER","BUS","CASE","COMPONENT",
    "CONFIGURATION","CONSTANT","DISCONNECT","DOWNTO","ELSE","ELSIF","END",
    "ENTITY","EXIT","FILE","FOR","FUNCTION","GENERATE","GENERIC","GUARDED",
    "IF","IN","INOUT","IS","LABEL","LIBRARY","LINKAGE","LOOP","MAP","MOD",
    "NAND","NEW","NEXT","NOR","NOT","NULL","OF","ON","OPEN","OR","OTHERS",
    "OUT","PACKAGE","PORT","PROCEDURE","PROCESS","RANGE","RECORD","REGISTER",
    "REM","REPORT","RETURN","SELECT","SEVERITY","SIGNAL","SUBTYPE","THEN","TO",
    "TRANSPORT","TYPE","UNITS","UNTIL","USE","VARIABLE","WAIT","WHEN","WHILE",
    "WITH","XOR"
	};
	for(int k=0;k < 81;k++) {keys.push_back(K[k]);}
}
