// The Haskell Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langhaskell.h"

LangHaskell ::LangHaskell() {

	fill();
	init_switches();


	doAdaComnt  = Yes;
	doHskComnt  = Yes;
}

void LangHaskell ::fill() {

	string K[] = {
  "abstract","case","concrete","data","do","in","interface","let","module",
  "native","of","open","private","public","sig","struct","type","use"
	};
	for(int k=0;k < 18;k++) {keys.push_back(K[k]);}
}
