// The Pascal Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_Pascal
#define LANG_DEF_Pascal

#include "lang_rules.h"

class LangPascal : public LanguageRules {

  public:
    LangPascal();
    void initReservedWords() override;
};

#endif // LANG_DEF_Pascal
