// The Tcl Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for modern Tcl (Tcl 8.6/9.0)

#include "langtcl.h"

#include <algorithm>
#include <iterator>

LangTcl ::LangTcl() {

	fill();
	init_switches();

	doScalars  = Yes;
	doUnxComnt = Yes;
}

void LangTcl ::fill() {

	// Tcl 8.6/9.0 keywords and core commands
	string K[] = {
		"after",
		"append",
		"apply",
		"array",
		"break",
		"catch",
		"cd",
		"chan",
		"close",
		"concat",
		"continue",
		"coroutine",
		"dict",
		"else",
		"elseif",
		"encoding",
		"eof",
		"error",
		"eval",
		"event",
		"exec",
		"exit",
		"expr",
		"file",
		"fileevent",
		"flush",
		"for",
		"foreach",
		"format",
		"gets",
		"glob",
		"global",
		"history",
		"if",
		"incr",
		"info",
		"interp",
		"join",
		"lappend",
		"lassign",
		"lindex",
		"linsert",
		"list",
		"llength",
		"lmap",
		"load",
		"lrange",
		"lrepeat",
		"lreplace",
		"lreverse",
		"lsearch",
		"lset",
		"lsort",
		"namespace",
		"oo",
		"open",
		"package",
		"pid",
		"proc",
		"puts",
		"pwd",
		"read",
		"regexp",
		"regsub",
		"rename",
		"return",
		"scan",
		"seek",
		"set",
		"socket",
		"source",
		"split",
		"string",
		"subst",
		"switch",
		"tailcall",
		"tell",
		"then",
		"throw",
		"time",
		"trace",
		"try",
		"unknown",
		"unset",
		"uplevel",
		"upvar",
		"variable",
		"vwait",
		"while",
		"yield",
		"yieldto",
		"zlib",
	};
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

	// Tcl 8.6/9.0 OO and type-related commands
	string T[] = {
		"binary",
		"boolean",
		"class",
		"clock",
		"constructor",
		"create",
		"define",
		"destroy",
		"destructor",
		"export",
		"filter",
		"forward",
		"method",
		"mixin",
		"new",
		"object",
		"self",
		"superclass",
		"unexport",
	};
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
