// The Ada Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for Ada 2022 (ISO/IEC 8652:2023)

#ifndef LANG_DEF_Ada
#define LANG_DEF_Ada

#include "engine.h"

class LangAda : public Engine {

  public:
    LangAda();
    ~LangAda() { IO->close(); }
    virtual void fill();
};

#endif // LANG_DEF_Ada
