// The ObjectiveC Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langobjc.h"

LangObjectiveC ::LangObjectiveC() {

	fill();
	init_switches();

	doSymbols  = Yes;
	doLabels   = Yes;
	doPreProc  = Yes;
	doArrays   = Yes;
	doBigComnt = Yes;
	doCinComnt = Yes;
}

void LangObjectiveC ::fill() {

	string K[] = {
		"Class","IMP","Nil","SEL","STR","bycopy","byref","id",
		"nil","self","super"
	};
	for(int k=0;k < 11;k++) {keys.push_back(K[k]);}

	string T[] = {
		"BOOL","in","inout","out","oneway"
	};
	for(int t=0;t < 5;t++) {types.push_back(T[t]);}
}
