// The ObjectiveC Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#include "langobjc.h"

#include <algorithm>
#include <iterator>
#include <string>

using std::string;

LangObjectiveC ::LangObjectiveC() {

    initReservedWords();

    doStringsSinQuote = true;
    doSymbols = true;
    doLabels = true;
    doPreProc = true;
    doBigComnt = true;
    doCinComnt = true;
}

void LangObjectiveC ::initReservedWords() {

    // Objective-C keywords (modern, through Xcode 16 / Clang 18)
    // Note: C keywords are inherited from LangC
    string K[] = {
        "__block",     "@autoreleasepool",
        "@available",  "@catch",
        "@class",      "@compatibility_alias",
        "@defs",       "@dynamic",
        "@encode",     "@end",
        "@finally",    "@implementation",
        "@import",     "@interface",
        "@optional",   "@package",
        "@private",    "@property",
        "@protected",  "@protocol",
        "@public",     "@required",
        "@selector",   "@synchronized",
        "@synthesize", "@throw",
        "@try",        "NO",
        "Nil",         "true",
        "nil",         "self",
        "super",
    };
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // Objective-C types
    string T[] = {
        "BOOL",
        "CGFloat",
        "CGPoint",
        "CGRect",
        "CGSize",
        "Class",
        "IMP",
        "NSArray",
        "NSBundle",
        "NSData",
        "NSDate",
        "NSDictionary",
        "NSError",
        "NSInteger",
        "NSMutableArray",
        "NSMutableDictionary",
        "NSMutableSet",
        "NSMutableString",
        "NSNotification",
        "NSNotificationCenter",
        "NSNumber",
        "NSObject",
        "NSSet",
        "NSString",
        "NSTimeInterval",
        "NSUInteger",
        "NSURL",
        "SEL",
        "bycopy",
        "byref",
        "id",
        "in",
        "inout",
        "instancetype",
        "nonnull",
        "null_resettable",
        "null_unspecified",
        "nullable",
        "oneway",
        "out",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
