// The Tcl Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_Tcl
#define LANG_DEF_Tcl

#include "engine.h"

class LangTcl : public Engine {

 public:
	LangTcl();
	~LangTcl() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_Tcl
