// The Basic Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_Basic
#define LANG_DEF_Basic

#include "engine.h"

class LangBasic : public Engine {

 public:
	LangBasic();
	~LangBasic() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_Basic
