
// The javascript Language definition file for Web C Plus Plus
// Generated by forrest johnston<forrest.johnston@attbi.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_JSCRIPT
#define LANG_DEF_JSCRIPT

#include "lang_rules.h"

class LangJScript : public LanguageRules {

  public:
    LangJScript();
    void initReservedWords() override;
};

#endif // LANG_DEF_JSCRIPT
