// The DOS Batch Language definition file for Web C Plus Plus
// Generated by Daniel Lin <dan@dlin.d2g.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langbatch.h"

LangBatch::LangBatch() {

	fill();
	init_switches();

//	doStrings   = No;
//	doNumbers   = No;
	doCaseKeys  = No;
//	doLabels    = Yes;
	doHashes    = Yes;
  doRemComnt  = Yes;
  doBatComnt  = Yes;
}

void LangBatch::fill() {
	string K[] = {
"assoc","at","attrib","break","cacls","call","cd","chcp","chdir","chkdsk",
"chkntfs","cls","cmd","color","comp","compact","control","convert","copy",
"date","del","dir","diskcomp","diskcopy","doskey","echo","endlocal",
"erase","exit","fc","find","findstr","for","format","ftype","goto",
"graftabl","help","if","label","md","mkdir","more","move","net","path",
"pause","popd","print","prompt","pushd","rd","recover","ren","rename",
"replace","rmdir","rundll32","set","setlocal","share","shift","sort",
"start","subst","time","title","tree","type","ver","verify","vol","xcopy"
	};
	for(int k=0;k < 73;k++) {keys.push_back(K[k]);}
}
