// The javascript Language definition file for Web C Plus Plus
// Generated by forrest johnston<forrest.johnston@attbi.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langjscript.h"

LangJScript ::LangJScript() {

	fill();
	init_switches();

	doSymbols   = Yes;
	doCinComnt  = Yes;
	doBigComnt  = Yes;
}

void LangJScript ::fill() {

	string K[] = {
"break",
"case",
"continue",
"default",
"delete",
"do",
"else",
"export",
"for",
"function",
"if",
"import",
"in",
"new",
"return",
"switch",
"this",
"typeof",
"var",
"void",
"while",
"with"
	};
	for(int k=0;k < 22;k++) {keys.push_back(K[k]);}
}

