// The VHDL Language definition file for Web C Plus Plus
// Generated by Thomas Hedler<thomas.hedler@fen-net.de> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_VHDL
#define LANG_DEF_VHDL

#include "engine.h"

class LangVHDL : public Engine {

 public:
	LangVHDL();
	~LangVHDL() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_VHDL
