// The CSharp Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langcsharp.h"

LangCSharp ::LangCSharp() {

	fill();
	init_switches();

	doSymbols  = Yes;
	doLabels   = Yes;
	doPreProc  = Yes;
	doBigComnt = Yes;
	doCinComnt = Yes;
}

void LangCSharp ::fill() {

	string K[] = {
		"abstract","as","base","break","case","catch","checked",
		"class","const","continue","default","do","else","enum",
		"event","explicit","extern","false","finally","fixed",
		"for","foreach","get","goto","if","implicit","in","interface",
		"internal","is","lock","namespace","new","null","operator",
		"override","params","private","protected","public","return",
		"sealed","set","sizeof","stackalloc","struct","switch","this",
		"throw","true","try","typeof","unchecked","unsafe","using",
		"value","virtual","while"
	};
	for(int k=0;k < 58;k++) {keys.push_back(K[k]);}

	string T[] = {
		"bool","byte","char","decimal","delegate","double","float",
		"int","long","object","readonly","ref","sbyte","short","static",
		"string","uint","ulong","out","ushort","void","volatile"
	};
	for(int t=0;t < 22;t++) {types.push_back(T[t]);}
}

