
// The Power Builder 6.x Language definition file for Web C Plus Plus
// Generated by Philippe Torche<philippe.torche@swissonline.ch> using
// genlang.cgi genlang.cgi Copyright (C) 2002 Jeffrey Bakker Webcpp Copyright
// (C)2001-2004, (C)2026 Jeffrey Bakker

#include "langpbuilder.h"

#include <algorithm>
#include <iterator>
#include <string>

using std::string;

LangPBuilder::LangPBuilder() {

    initReservedWords();

    doStringsSinQuote = true;
    doCaseKeys = false;
    doInlineCommentDblSlash = true;
    doBlockCommentPLI = true;
}

void LangPBuilder::initReservedWords() {

    string K[] = {"_debug",
                  "alias",
                  "and",
                  "autoinstantiate",
                  "blob",
                  "boolean",
                  "call",
                  "case",
                  "char",
                  "character",
                  "choose",
                  "close",
                  "commit",
                  "connect",
                  "constant",
                  "continue",
                  "create",
                  "cursor",
                  "date",
                  "datetime",
                  "dec",
                  "decimal",
                  "declare",
                  "delete",
                  "describe",
                  "descriptor",
                  "destroy",
                  "disconnect",
                  "do",
                  "double",
                  "dynamic",
                  "else",
                  "elseif",
                  "end",
                  "enumerated",
                  "event",
                  "execute",
                  "exit",
                  "external",
                  "false",
                  "fetch",
                  "first",
                  "for",
                  "forward",
                  "from",
                  "function",
                  "global",
                  "goto",
                  "halt",
                  "if",
                  "immediate",
                  "indirect",
                  "insert",
                  "int",
                  "integer",
                  "into",
                  "intrinsic",
                  "is",
                  "last",
                  "library",
                  "long",
                  "loop",
                  "next",
                  "not",
                  "of",
                  "on",
                  "open",
                  "or",
                  "parent",
                  "post",
                  "prepare",
                  "prior",
                  "private",
                  "privateread",
                  "privatewrite",
                  "procedure",
                  "protected",
                  "protectedread",
                  "protectedwrite",
                  "prototypes",
                  "public",
                  "readonly",
                  "real",
                  "ref",
                  "return",
                  "rollback",
                  "rpcfunc",
                  "select",
                  "selectblob",
                  "shared",
                  "static",
                  "step",
                  "string",
                  "subroutine",
                  "super",
                  "system",
                  "systemread",
                  "systemwrite",
                  "then",
                  "this",
                  "time",
                  "to",
                  "trigger",
                  "true",
                  "type",
                  "uint",
                  "ulong",
                  "unsignedint",
                  "unsignedinteger",
                  "unsignedlong",
                  "until",
                  "update",
                  "updateblob",
                  "using",
                  "variables",
                  "while",
                  "with",
                  "within"};
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));
}
