// Author: Jeffrey Bakker  |  Date: May14th 2002  |  langasm.cpp

// the Assembler Language definition file for Web C Plus Plus
// Webcpp Copyright (C) 2002 Jeffrey Bakker
// Updated 2026 for modern x86-64, SSE/AVX/AVX-512, and ARM AArch64/NEON

#include "langasm.h"

#include <algorithm>
#include <iterator>

LangAssembler::LangAssembler() {

	fill();
	init_switches();

	doCaseKeys  = No;
	doLabels    = Yes;
	doPreProc   = Yes;
	doBigComnt  = Yes;
	doAsmComnt  = Yes;
}

void LangAssembler::fill() {

	// Instructions and assembler directives (1482 entries)
	// x86/x86-64, SSE/SSE2/SSE3/SSE4, AVX/AVX2, AVX-512,
	// ARM AArch64, ARM NEON/SIMD, GNU/MASM/NASM directives
	string K[] = {
		// GNU assembler directives
		".abort",".align",".altmacro",".ascii",".asciz",
		".balign",".bss",".byte",
		".cfi_def_cfa",".cfi_def_cfa_offset",".cfi_endproc",".cfi_offset",
		".cfi_startproc",".comm",
		".data",".def",".double",
		".else",".elseif",".end",".endef",".endif",".endm",".endr",
		".equ",".equiv",".err",".even",".extern",
		".file",".fill",".float",
		".global",".globl",
		".hidden",
		".if",".ifdef",".ifndef",".include",".int",".irp",".irpc",
		".lcomm",".local",".long",".ltorg",
		".macro",
		".noaltmacro",
		".octa",".offset",".org",
		".p2align",".popsection",".previous",".protected",".pushsection",
		".quad",
		".rept",
		".section",".set",".short",".single",".size",".skip",".sleb128",
		".space",".string",".struct",".subsection",".symver",
		".text",".thumb",".thumb_func",".type",
		".uleb128",
		".value",".version",".vtable_entry",
		".warning",".weak",".word",
		".zero",

		// x86/x86-64 instructions, SSE/AVX/AVX-512, ARM AArch64/NEON,
		// MASM/NASM directives — sorted alphabetically
		"aam","aas","abs","adc","adcs","adcx","add","addp","addpd","addps",
		"adds","addsd","addss","addsubpd","addsubps","addv","adox","adr","adrp",
		"aesd","aesdec","aesdeclast","aese","aesenc","aesenclast","aesimc",
		"aeskeygenassist","aesmc","align","and","andn","andnpd","andnps",
		"andpd","andps","ands","arpl","asr","assume","at",
		"autda","autdb","autia","autiasp","autib","autibsp",
		"b","b.al","b.cc","b.cs","b.eq","b.ge","b.gt","b.hi","b.le","b.ls",
		"b.lt","b.mi","b.ne","b.pl","b.vc","b.vs",
		"bextr","bic","bics","bif","bit","bits","bl","blendpd","blendps",
		"blendvpd","blendvps","blr","blsi","blsmsk","blsr","bne","bound",
		"bpl","br","bsf","bsl","bsr","bswap","bt","btc","bti","btr","bts",
		"byte","bzhi",
		"call","cas","casa","casal","casl","cbnz","cbw","cbz","ccmn","ccmp",
		"cdq","cdqe","clc","cld","clflush","clflushopt","clrex","cls","clts",
		"clwb","clz","cmc","cmeq","cmge","cmgt","cmhi","cmhs","cmle","cmlt",
		"cmova","cmovae","cmovb","cmovbe","cmovc","cmove","cmovg","cmovge",
		"cmovl","cmovle","cmovna","cmovnae","cmovnb","cmovnbe","cmovnc",
		"cmovne","cmovng","cmovnge","cmovnl","cmovnle","cmovno","cmovnp",
		"cmovns","cmovnz","cmovo","cmovp","cmovpe","cmovpo","cmovs","cmovz",
		"cmp","cmppd","cmpps","cmpsb","cmpsd","cmpsq","cmpss","cmpsw",
		"cmpxchg","cmpxchg16b","cmpxchg8b","cmtst","cnt","comisd","comiss",
		"cpuid","cqo","crc32","crc32b","crc32cb","crc32ch","crc32cw","crc32cx",
		"crc32h","crc32w","crc32x",
		"csel","cset","csetm","csinc","csinv","csneg",
		"cvtdq2pd","cvtdq2ps","cvtpd2dq","cvtpd2pi","cvtpd2ps","cvtpi2pd",
		"cvtpi2ps","cvtps2dq","cvtps2pd","cvtps2pi","cvtsd2si","cvtsd2ss",
		"cvtsi2sd","cvtsi2ss","cvtss2sd","cvtss2si","cvttpd2dq","cvttps2dq",
		"cvttsd2si","cvttss2si","cwd","cwde",
		"daa","das","db","dc","dd","dec","div","divpd","divps","divsd","divss",
		"dmb","dppd","dpps","dq","dsb","dt","dup","dw","dword",
		"else","elseif","end","endbr32","endbr64","endif","endm","endp","ends",
		"enter","eon","eor","equ","eret","ext","extern","extr","extractps","extrn",
		"fabs","fadd","faddp","far","fccmp","fccmpe","fchs","fcmeq","fcmge",
		"fcmgt","fcmle","fcmlt","fcmp","fcmpe","fcom","fcomi","fcomip","fcomp",
		"fcompp","fcos","fcsel","fcvt","fcvtas","fcvtau","fcvtms","fcvtmu",
		"fcvtns","fcvtnu","fcvtps","fcvtpu","fcvtzs","fcvtzu","fdiv","fdivp",
		"fild","finit","fist","fistp","fld","fld1","fldcw","fldpi","fldz",
		"fmadd","fmax","fmaxnm","fmin","fminnm","fmla","fmls","fmov","fmsub",
		"fmul","fmulp","fneg","fninit","fnmadd","fnmsub","fnstcw","fnstsw",
		"fpatan","fptan","frecpe","frecps","frint32z","frint64z","frinta",
		"frinti","frintm","frintn","frintp","frintx","frintz","frsqrte",
		"frsqrts","fsin","fsqrt","fst","fstcw","fstp","fstsw","fsub","fsubp",
		"fucom","fucomi","fucomip","fucomp","fucompp","fwait","fxch",
		"global","group",
		"haddpd","haddps","hint","hlt","hsubpd","hsubps","hvc",
		"ic","idiv","if","ifdef","ifndef","imul","in","inc","incbin","include",
		"ins","insertps","int","int3","into","iret","isb",
		"ja","jae","jb","jbe","jc","jcxz","je","jecxz","jg","jge","jl","jle",
		"jmp","jnae","jnb","jnbe","jnc","jne","jng","jnl","jno","jnp","jns",
		"jnz","jo","jp","jpe","jpo","jrcxz","js","jz",
		"kandnw","kandw","kmovb","kmovd","kmovq","kmovw","knotw","kortestw",
		"korw","kshiftlw","kshiftrw","ktestw","kunpckbw","kxnorw","kxorw",
		"label","lahf",
		"ld1","ld1r","ld2","ld2r","ld3","ld3r","ld4","ld4r",
		"ldadd","ldaddal","ldar","ldaxr","ldclr","lddqu","ldeor","ldnp","ldp",
		"ldr","ldraa","ldrab","ldrb","ldrex","ldrh","ldrsb","ldrsh","ldrsw",
		"lds","ldset","ldtr","ldur","ldxr",
		"lea","leave","les","lfence","lfs","lgs","local",
		"lodsb","lodsd","lodsq","lodsw","loop","loope","loopne","loopnz","loopz",
		"lsl","lsr","lss","lzcnt",
		"macro","madd","main","maxpd","maxps","maxsd","maxss","mfence",
		"minpd","minps","minsd","minss","mla","mls","mneg",
		"mov","movapd","movaps","movbe","movd","movddup","movdqa","movdqu",
		"movhpd","movhps","movi","movk","movlpd","movlps","movmskpd","movmskps",
		"movn","movntdq","movnti","movntpd","movntps","movps","movq","movsb",
		"movsd","movshdup","movsldup","movsq","movss","movsw","movsx","movsxd",
		"movupd","movups","movz","movzx",
		"mpsadbw","mrs","msr","msub","mul","mulpd","mulps","mulsd","mulss",
		"mulx","mvn","mvni",
		"near","neg","negs","ngc","ngcs","nop","not",
		"offset","or","org","orn","orpd","orps","orr","out",
		"pabsb","pabsd","pabsw","pacda","pacdb","pacia","paciasp","pacib",
		"pacibsp","packssdw","packsswb","packusdw","packuswb",
		"paddb","paddd","paddq","paddsb","paddsw","paddusb","paddusw","paddw",
		"palignr","pand","pandn","pause","pavgb","pavgw",
		"pblendvb","pblendw","pclmulqdq",
		"pcmpeqb","pcmpeqd","pcmpeqq","pcmpeqw","pcmpestri","pcmpestrm",
		"pcmpgtb","pcmpgtd","pcmpgtq","pcmpgtw","pcmpistri","pcmpistrm",
		"pdep","pext","pextrb","pextrd","pextrq","pextrw",
		"phaddd","phaddsw","phaddw","phsubd","phsubsw","phsubw",
		"pinsrb","pinsrd","pinsrq","pinsrw",
		"pmaddubsw","pmaddwd",
		"pmaxsb","pmaxsd","pmaxsw","pmaxub","pmaxud","pmaxuw",
		"pminsb","pminsd","pminsw","pminub","pminud","pminuw",
		"pmovmskb","pmovsxbd","pmovsxbq","pmovsxbw","pmovsxdq","pmovsxwd",
		"pmovsxwq","pmovzxbd","pmovzxbq","pmovzxbw","pmovzxdq","pmovzxwd",
		"pmovzxwq","pmul","pmuldq","pmulhuw","pmulhw","pmull","pmulld",
		"pmullw","pmuludq",
		"pop","popa","popad","popcnt","popf","popfd","popfq","por",
		"prefetch","prefetchnta","prefetcht0","prefetcht1","prefetcht2",
		"prfm","proc","proto","psadbw",
		"pshufb","pshufd","pshufhw","pshuflw","pshufw",
		"psignb","psignd","psignw",
		"pslld","psllq","psllw","psrad","psraw","psrld","psrlq","psrlw",
		"psubb","psubd","psubq","psubsb","psubsw","psubusb","psubusw","psubw",
		"ptest","ptr","public",
		"punpckhbw","punpckhdq","punpckhqdq","punpckhwd",
		"punpcklbw","punpckldq","punpcklqdq","punpcklwd",
		"push","pusha","pushad","pushf","pushfd","pushfq","pxor",
		"qword",
		"rbit","rcl","rcpps","rcpss","rcr","rdtsc","rdtscp",
		"record","rep","repe","repne","repnz","rept","repz","ret",
		"rev","rev16","rev32","rev64","rol","ror","rorx",
		"roundpd","roundps","roundsd","roundss",
		"rshrn","rsqrtps","rsqrtss",
		"saba","sabal","sabd","sabdl","sadalp","saddl","saddlp","saddw",
		"sahf","sal","sar","sarx","sbb","sbc","sbcs",
		"scasb","scasd","scasq","scasw","scvtf","sdiv",
		"section","seg","segment",
		"seta","setae","setb","setbe","setc","sete","setg","setge",
		"setl","setle","setna","setnae","setnb","setnbe","setnc","setne",
		"setng","setnge","setnl","setnle","setno","setnp","setns","setnz",
		"seto","setp","setpe","setpo","sets","setz",
		"sev","sevl","sfence",
		"sha1c","sha1h","sha1m","sha1p","sha1su0","sha1su1",
		"sha256h","sha256h2","sha256su0","sha256su1",
		"shl","shld","shlx","short","shr","shrd","shrn","shrx",
		"shufpd","shufps","sli",
		"smax","smaxp","smaxv","smc","smin","sminp","sminv",
		"smlal","smlsl","smov","smulh","smull",
		"sqabs","sqadd","sqneg","sqrshl","sqrshrn","sqrshrun",
		"sqrtpd","sqrtps","sqrtsd","sqrtss",
		"sqshl","sqshrn","sqshrun","sqsub",
		"sri","srshl","srshr","sshl","sshll","sshr",
		"ssubl","ssubw",
		"st1","st2","st3","st4",
		"stadd","stc","stclr","std","steor","stlr","stlxr","stnp",
		"stosb","stosd","stosq","stosw","stp","str","strb","strex","strh",
		"struc","struct","stset","sttr","stur","stxr",
		"sub","subpd","subps","subs","subsd","subss","svc","swp","swpal",
		"sxtb","sxth","sxtw","syscall","sysenter","sysexit","sysret",
		"tbl","tbnz","tbx","tbz","test","textequ","times","title","tlbi",
		"trn1","trn2","tst","typedef","tzcnt",
		"uaba","uabal","uabd","uabdl","uadalp","uaddl","uaddlp","uaddw",
		"ucomisd","ucomiss","ucvtf","ud2","udiv",
		"umax","umaxp","umaxv","umin","uminp","uminv",
		"umlal","umlsl","umov","umulh","umull","union",
		"unpckhpd","unpckhps","unpcklpd","unpcklps",
		"uqadd","uqrshl","uqrshrn","uqshl","uqshrn","uqsub",
		"urshl","urshr","use16","use32","use64",
		"ushl","ushll","ushr","usubl","usubw",
		"uxtb","uxth","uxtw","uzp1","uzp2",
		"vaddpd","vaddps","vaddsd","vaddss",
		"vandnpd","vandnps","vandpd","vandps",
		"vblendpd","vblendps","vblendvpd","vblendvps",
		"vbroadcastf128","vbroadcastf32x4","vbroadcastf64x4",
		"vbroadcasti128","vbroadcasti32x4","vbroadcasti64x4",
		"vbroadcastsd","vbroadcastss",
		"vcmppd","vcmpps","vcmpsd","vcmpss",
		"vcomisd","vcomiss","vcompresspd","vcompressps",
		"vcvtdq2pd","vcvtdq2ps","vcvtpd2dq","vcvtpd2ps",
		"vcvtpd2qq","vcvtpd2udq","vcvtpd2uqq",
		"vcvtps2dq","vcvtps2pd","vcvtps2qq","vcvtps2udq","vcvtps2uqq",
		"vcvtqq2pd","vcvtqq2ps",
		"vcvtsd2si","vcvtsd2ss","vcvtsi2sd","vcvtsi2ss",
		"vcvtss2sd","vcvtss2si",
		"vcvttpd2dq","vcvttpd2qq","vcvttpd2udq","vcvttpd2uqq",
		"vcvttps2dq","vcvttps2qq","vcvttps2udq","vcvttps2uqq",
		"vcvttsd2si","vcvttss2si",
		"vcvtudq2pd","vcvtudq2ps","vcvtuqq2pd","vcvtuqq2ps",
		"vdbpsadbw","vdivpd","vdivps","vdivsd","vdivss","vdppd","vdpps",
		"vexpandpd","vexpandps",
		"vextractf128","vextractf32x4","vextractf64x4",
		"vextracti128","vextracti32x4","vextracti64x4","vextractps",
		"vfixupimmpd","vfixupimmps","vfixupimmsd","vfixupimmss",
		"vfmadd132pd","vfmadd132ps","vfmadd132sd","vfmadd132ss",
		"vfmadd213pd","vfmadd213ps","vfmadd213sd","vfmadd213ss",
		"vfmadd231pd","vfmadd231ps","vfmadd231sd","vfmadd231ss",
		"vfmsub132pd","vfmsub132ps","vfmsub213pd","vfmsub213ps",
		"vfmsub231pd","vfmsub231ps",
		"vfnmadd132pd","vfnmadd132ps","vfnmadd213pd","vfnmadd213ps",
		"vfnmadd231pd","vfnmadd231ps",
		"vfnmsub132pd","vfnmsub132ps","vfnmsub213pd","vfnmsub213ps",
		"vfnmsub231pd","vfnmsub231ps",
		"vfpclasspd","vfpclassps","vfpclasssd","vfpclassss",
		"vgatherdpd","vgatherdps","vgatherqpd","vgatherqps",
		"vgetexppd","vgetexpps","vgetexpsd","vgetexpss",
		"vgetmantpd","vgetmantps","vgetmantsd","vgetmantss",
		"vhaddpd","vhaddps","vhsubpd","vhsubps",
		"vinsertf128","vinsertf32x4","vinsertf64x4",
		"vinserti128","vinserti32x4","vinserti64x4","vinsertps",
		"vmaskmovpd","vmaskmovps",
		"vmaxpd","vmaxps","vmaxsd","vmaxss",
		"vminpd","vminps","vminsd","vminss",
		"vmovapd","vmovaps","vmovd","vmovddup","vmovdqa","vmovdqa32",
		"vmovdqa64","vmovdqu","vmovdqu16","vmovdqu32","vmovdqu64","vmovdqu8",
		"vmovhpd","vmovhps","vmovlpd","vmovlps",
		"vmovmskpd","vmovmskps","vmovntdq","vmovntpd","vmovntps",
		"vmovq","vmovsd","vmovshdup","vmovsldup","vmovss","vmovupd","vmovups",
		"vmpsadbw","vmulpd","vmulps","vmulsd","vmulss",
		"vorpd","vorps",
		"vpabsb","vpabsd","vpabsq","vpabsw",
		"vpackssdw","vpacksswb","vpackusdw","vpackuswb",
		"vpaddb","vpaddd","vpaddq","vpaddsb","vpaddsw",
		"vpaddusb","vpaddusw","vpaddw",
		"vpalignr","vpand","vpandn","vpavgb","vpavgw",
		"vpblendd","vpblendvb","vpblendw",
		"vpbroadcastb","vpbroadcastd","vpbroadcastmb2q","vpbroadcastmw2d",
		"vpbroadcastq","vpbroadcastw",
		"vpcmpb","vpcmpd","vpcmpeqb","vpcmpeqd","vpcmpeqq","vpcmpeqw",
		"vpcmpgtb","vpcmpgtd","vpcmpgtq","vpcmpgtw",
		"vpcmpq","vpcmpub","vpcmpud","vpcmpuq","vpcmpuw","vpcmpw",
		"vpcompressd","vpcompressq","vpconflictd","vpconflictq",
		"vperm2f128","vperm2i128","vpermb","vpermd","vpermi2d","vpermi2pd",
		"vpermi2ps","vpermi2q","vpermpd","vpermps","vpermq",
		"vpermt2d","vpermt2pd","vpermt2ps","vpermt2q","vpermw",
		"vpexpandd","vpexpandq",
		"vpextrb","vpextrd","vpextrq","vpextrw",
		"vpgatherdd","vpgatherdq","vpgatherqd","vpgatherqq",
		"vphaddd","vphaddsw","vphaddw","vphsubd","vphsubsw","vphsubw",
		"vpinsrb","vpinsrd","vpinsrq","vpinsrw",
		"vplzcntd","vplzcntq",
		"vpmaddubsw","vpmaddwd",
		"vpmaskmovd","vpmaskmovq",
		"vpmaxsb","vpmaxsd","vpmaxsq","vpmaxsw",
		"vpmaxub","vpmaxud","vpmaxuq","vpmaxuw",
		"vpminsb","vpminsd","vpminsq","vpminsw",
		"vpminub","vpminud","vpminuq","vpminuw",
		"vpmovdb","vpmovdw","vpmovmskb","vpmovqb","vpmovqd","vpmovqw",
		"vpmovsdb","vpmovsdw","vpmovsqb","vpmovsqd","vpmovsqw",
		"vpmovsxbd","vpmovsxbq","vpmovsxbw","vpmovsxdq","vpmovsxwd","vpmovsxwq",
		"vpmovusdb","vpmovusdw","vpmovusqb","vpmovusqd","vpmovusqw",
		"vpmovzxbd","vpmovzxbq","vpmovzxbw","vpmovzxdq","vpmovzxwd","vpmovzxwq",
		"vpmuldq","vpmulhuw","vpmulhw","vpmulld","vpmullq","vpmullw","vpmuludq",
		"vpor",
		"vprold","vprolq","vprolvd","vprolvq",
		"vprord","vprorq","vprorvd","vprorvq",
		"vpsadbw",
		"vpscatterdd","vpscatterdq","vpscatterqd","vpscatterqq",
		"vpshufb","vpshufd","vpshufhw","vpshuflw",
		"vpsignb","vpsignd","vpsignw",
		"vpslld","vpsllq","vpsllvd","vpsllvq","vpsllw",
		"vpsrad","vpsravd","vpsraw",
		"vpsrld","vpsrlq","vpsrlvd","vpsrlvq","vpsrlw",
		"vpsubb","vpsubd","vpsubq","vpsubsb","vpsubsw",
		"vpsubusb","vpsubusw","vpsubw",
		"vpternlogd","vpternlogq","vptest",
		"vptestmb","vptestmd","vptestmq","vptestmw",
		"vptestnmb","vptestnmd","vptestnmq","vptestnmw",
		"vpunpckhbw","vpunpckhdq","vpunpckhqdq","vpunpckhwd",
		"vpunpcklbw","vpunpckldq","vpunpcklqdq","vpunpcklwd",
		"vpxor",
		"vrangepd","vrangeps","vrangesd","vrangess",
		"vrcp14pd","vrcp14ps","vrcp14sd","vrcp14ss","vrcpps","vrcpss",
		"vreducepd","vreduceps","vreducesd","vreducess",
		"vrndscalepd","vrndscaleps","vrndscalesd","vrndscaless",
		"vroundpd","vroundps","vroundsd","vroundss",
		"vrsqrt14pd","vrsqrt14ps","vrsqrt14sd","vrsqrt14ss","vrsqrtps","vrsqrtss",
		"vscalefpd","vscalefps","vscalefsd","vscalefss",
		"vscatterdpd","vscatterdps","vscatterqpd","vscatterqps",
		"vshufpd","vshufps",
		"vsqrtpd","vsqrtps","vsqrtsd","vsqrtss",
		"vsubpd","vsubps","vsubsd","vsubss",
		"vucomisd","vucomiss",
		"vunpckhpd","vunpckhps","vunpcklpd","vunpcklps",
		"vxorpd","vxorps","vzeroall","vzeroupper",
		"wait","wfe","wfi","word",
		"xchg","xgetbv","xlat","xlatb","xor","xorpd","xorps","xrstor","xsave",
		"xsetbv",
		"yield","zip1","zip2",
	};
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

	// Registers (473 entries)
	// x86/x86-64, x87 FPU, MMX, SSE, AVX, AVX-512,
	// ARM AArch64, ARM NEON/SIMD, segment, control, debug
	string T[] = {
		// x86 8/16-bit registers
		"ah","al","ax",
		// ARM NEON byte registers b0-b31
		"b0","b1","b10","b11","b12","b13","b14","b15","b16","b17","b18","b19",
		"b2","b20","b21","b22","b23","b24","b25","b26","b27","b28","b29",
		"b3","b30","b31","b4","b5","b6","b7","b8","b9",
		// x86 8/16-bit registers
		"bh","bl","bp","bpl","bx",
		// x86 8/16-bit, control, segment registers
		"ch","cl","cr0","cr1","cr2","cr3","cr4","cs","cx",
		// ARM NEON double registers d0-d31
		"d0","d1","d10","d11","d12","d13","d14","d15","d16","d17","d18","d19",
		"d2","d20","d21","d22","d23","d24","d25","d26","d27","d28","d29",
		"d3","d30","d31","d4","d5","d6","d7","d8","d9",
		// x86 8/16-bit, debug, segment registers
		"dh","di","dil","dl",
		"dr0","dr1","dr2","dr3","dr4","dr5","dr6","dr7",
		"ds","dx",
		// x86 32-bit registers
		"eax","ebx","ecx","edi","edx","eflags","eip","es","esi",
		// Flags and special registers
		"flags","fp","fpcr","fpsr","fs",
		// Segment register
		"gs",
		// ARM NEON half registers h0-h31
		"h0","h1","h10","h11","h12","h13","h14","h15","h16","h17","h18","h19",
		"h2","h20","h21","h22","h23","h24","h25","h26","h27","h28","h29",
		"h3","h30","h31","h4","h5","h6","h7","h8","h9",
		// Instruction pointer
		"ip",
		// AVX-512 mask registers k0-k7
		"k0","k1","k2","k3","k4","k5","k6","k7",
		// ARM link register
		"lr",
		// x86 MMX registers mm0-mm7
		"mm0","mm1","mm2","mm3","mm4","mm5","mm6","mm7",
		// SSE control register
		"mxcsr",
		// ARM condition flags
		"nzcv",
		// ARM NEON quad registers q0-q31
		"q0","q1","q10","q11","q12","q13","q14","q15","q16","q17","q18","q19",
		"q2","q20","q21","q22","q23","q24","q25","q26","q27","q28","q29",
		"q3","q30","q31","q4","q5","q6","q7","q8","q9",
		// x86-64 extended registers r8-r15 (64/32/16/8-bit)
		"r10","r10b","r10d","r10w","r11","r11b","r11d","r11w",
		"r12","r12b","r12d","r12w","r13","r13b","r13d","r13w",
		"r14","r14b","r14d","r14w","r15","r15b","r15d","r15w",
		"r8","r8b","r8d","r8w","r9","r9b","r9d","r9w",
		// x86-64 general purpose registers
		"rax","rbp","rbx","rcx","rdi","rdx","rflags","rip","rsi","rsp",
		// ARM NEON single registers s0-s31
		"s0","s1","s10","s11","s12","s13","s14","s15","s16","s17","s18","s19",
		"s2","s20","s21","s22","s23","s24","s25","s26","s27","s28","s29",
		"s3","s30","s31","s4","s5","s6","s7","s8","s9",
		// x86 16-bit, low-byte, stack, segment registers
		"si","sil","sp","spl","ss",
		// x87 FPU stack registers
		"st0","st1","st2","st3","st4","st5","st6","st7",
		// ARM NEON vector registers v0-v31
		"v0","v1","v10","v11","v12","v13","v14","v15","v16","v17","v18","v19",
		"v2","v20","v21","v22","v23","v24","v25","v26","v27","v28","v29",
		"v3","v30","v31","v4","v5","v6","v7","v8","v9",
		// ARM AArch64 32-bit registers w0-w30
		"w0","w1","w10","w11","w12","w13","w14","w15","w16","w17","w18","w19",
		"w2","w20","w21","w22","w23","w24","w25","w26","w27","w28","w29",
		"w3","w30","w4","w5","w6","w7","w8","w9",
		// ARM zero register (32-bit)
		"wzr",
		// ARM AArch64 64-bit registers x0-x30
		"x0","x1","x10","x11","x12","x13","x14","x15","x16","x17","x18","x19",
		"x2","x20","x21","x22","x23","x24","x25","x26","x27","x28","x29",
		"x3","x30","x4","x5","x6","x7","x8","x9",
		// SSE registers xmm0-xmm31
		"xmm0","xmm1","xmm10","xmm11","xmm12","xmm13","xmm14","xmm15",
		"xmm16","xmm17","xmm18","xmm19","xmm2","xmm20","xmm21","xmm22",
		"xmm23","xmm24","xmm25","xmm26","xmm27","xmm28","xmm29","xmm3",
		"xmm30","xmm31","xmm4","xmm5","xmm6","xmm7","xmm8","xmm9",
		// ARM zero register (64-bit)
		"xzr",
		// AVX registers ymm0-ymm31
		"ymm0","ymm1","ymm10","ymm11","ymm12","ymm13","ymm14","ymm15",
		"ymm16","ymm17","ymm18","ymm19","ymm2","ymm20","ymm21","ymm22",
		"ymm23","ymm24","ymm25","ymm26","ymm27","ymm28","ymm29","ymm3",
		"ymm30","ymm31","ymm4","ymm5","ymm6","ymm7","ymm8","ymm9",
		// AVX-512 registers zmm0-zmm31
		"zmm0","zmm1","zmm10","zmm11","zmm12","zmm13","zmm14","zmm15",
		"zmm16","zmm17","zmm18","zmm19","zmm2","zmm20","zmm21","zmm22",
		"zmm23","zmm24","zmm25","zmm26","zmm27","zmm28","zmm29","zmm3",
		"zmm30","zmm31","zmm4","zmm5","zmm6","zmm7","zmm8","zmm9",
	};
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
