// The CSharp Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_CSharp
#define LANG_DEF_CSharp

#include "engine.h"

class LangCSharp : public Engine {

  public:
    LangCSharp();
    ~LangCSharp() { IO->close(); }
    virtual void fill();
};

#endif // LANG_DEF_CSharp
