// The RenderMan Shading Language definition file for Web C Plus Plus
// Generated by Mark Williams <markdjwilliams@hotmail.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for RenderMan RSL and Open Shading Language (OSL)

#ifndef LANG_DEF_RENDERMAN_SHADING_LANGUAGE
#define LANG_DEF_RENDERMAN_SHADING_LANGUAGE

#include "engine.h"

class LangRenderMan : public Engine {

  public:
    LangRenderMan();
    void fill() override;
};

#endif // LANG_DEF_RENDERMAN_SHADING_LANGUAGE
