
// The Cg Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#ifndef LANG_DEF_NVIDIA_CG_SHADING_LANGUAGE
#define LANG_DEF_NVIDIA_CG_SHADING_LANGUAGE

#include "lang_rules.h"

class LangCg : public LanguageRules {

  public:
    LangCg();
    void initReservedWords() override;
};

#endif // LANG_DEF_NVIDIA_CG_SHADING_LANGUAGE
