// The Pascal Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker<jefskey@yahoo.com> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_Pascal
#define LANG_DEF_Pascal

#include "engine.h"

class LangPascal : public Engine {

 public:
	LangPascal();
	~LangPascal() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_Pascal
