// The CLIPS Language definition file for Web C Plus Plus
// Generated by Walter Maner<maner@cs.bgsu.edu> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#ifndef LANG_DEF_NASA_CLIPS
#define LANG_DEF_NASA_CLIPS

#include "engine.h"

class LangClips : public Engine {

 public:
	LangClips();
	~LangClips() {IO->close();}
	virtual void fill();

};

#endif //LANG_DEF_NASA_CLIPS

