// The emf Language definition file for Web C Plus Plus
// Generated by Dr. Detlef Groth<dgroth@gmx.de> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#include "langemf.h"

#include <algorithm>
#include <iterator>

using std::string;

LangEmf ::LangEmf() {

    initReservedWords();

    doStringsSinQuote = true;
    doStringsBackTick = true;
    doNumbers = false;
    doUnderscoreNumbers = true;
    doLabels = true;
    doScalars = true;
    doArrays = true;
    doHashes = true;
    doInlineCommentSemiColon = true;
}

void LangEmf ::initReservedWords() {

    string K[] = {"!abort",        "!bell",   "!continue",     "!done",
                  "!ehelp",        "!elif",   "!else",         "!emacro",
                  "!end",          "!endif",  "!force",        "!goto",
                  "!if",           "!iif",    "!jump",         "!nmacro",
                  "!repeat",       "!return", "!tgoto",        "!tjump",
                  "!until",        "!while",  "0define-macro", "define-macro",
                  "undefine-macro"};
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));
}
