// The Basic Language definition file for Web C Plus Plus
// Generated by Jeffrey Bakker using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker

#include "langbasic.h"

#include <algorithm>
#include <iterator>

LangBasic ::LangBasic() {

	fill();
	init_switches();

	doCaseKeys = No;
	doLabels   = Yes;
	doAsmComnt = Yes;
	doRemComnt = Yes;
}

void LangBasic ::fill() {

	string K[] = {
	"ABS","AND","ASC","BYE","CHR","CLS","DATA","DEL","DIM","END","FOR","GOSUB",
	"GOTO","IF","INPUT","LEN","LET","LIST","LOAD","LOCATE","LOG","MERGE","MID",
	"MOD","NEW","NEXT","NOT","ON","OR","POKE","PRINT","RAND","READ","RENUM",
	"RESTORE","RETURN","RND","RUN","SAVE","SGN","SIN","SQR","SQRT","STOP",
	"STR","TO","VAL","WEND","WHILE","XOR"
	};
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));
}
