// The CLIPS Language definition file for Web C Plus Plus
// Generated by Walter Maner<maner@cs.bgsu.edu> using genlang.cgi
// genlang.cgi Copyright (C) 2002 Jeffrey Bakker
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker
// Updated 2026 for CLIPS 6.4

#ifndef LANG_DEF_NASA_CLIPS
#define LANG_DEF_NASA_CLIPS

#include "lang_rules.h"

class LangClips : public LanguageRules {

  public:
    LangClips();
    void initReservedWords() override;
};

#endif // LANG_DEF_NASA_CLIPS
