// langcss.cpp

// the CSS Language definition file for Web C Plus Plus
// Webcpp Copyright (C)2001-2004, (C)2026 Jeffrey Bakker

#include "langcss.h"

#include <algorithm>
#include <iterator>
#include <string>

using std::string;

LangCSS::LangCSS() {

    initReservedWords();

    doStringsSinQuote = true;
    doCaseKeys = false;
    doBlockCommentPLI = true;
    doNumbers = true;
}

void LangCSS::initReservedWords() {

    // CSS at-rules and selectors
    string K[] = {
        "@charset",
        "@color-profile",
        "@container",
        "@counter-style",
        "@font-face",
        "@font-feature-values",
        "@font-palette-values",
        "@import",
        "@keyframes",
        "@layer",
        "@media",
        "@namespace",
        "@page",
        "@property",
        "@scope",
        "@starting-style",
        "@supports",
        "@view-transition",
        "!important",
        "all",
        "and",
        "from",
        "inherit",
        "initial",
        "none",
        "not",
        "only",
        "or",
        "revert",
        "to",
        "unset",
    };
    std::copy(std::cbegin(K), std::cend(K), std::back_inserter(keys));

    // CSS common properties
    string T[] = {
        "align-content",
        "align-items",
        "align-self",
        "animation",
        "appearance",
        "aspect-ratio",
        "background",
        "background-color",
        "background-image",
        "background-position",
        "background-repeat",
        "background-size",
        "border",
        "border-bottom",
        "border-collapse",
        "border-color",
        "border-left",
        "border-radius",
        "border-right",
        "border-style",
        "border-top",
        "border-width",
        "bottom",
        "box-shadow",
        "box-sizing",
        "clear",
        "clip-path",
        "color",
        "column-count",
        "column-gap",
        "container-type",
        "content",
        "cursor",
        "direction",
        "display",
        "filter",
        "flex",
        "flex-basis",
        "flex-direction",
        "flex-flow",
        "flex-grow",
        "flex-shrink",
        "flex-wrap",
        "float",
        "font",
        "font-family",
        "font-size",
        "font-style",
        "font-variant",
        "font-weight",
        "gap",
        "grid",
        "grid-area",
        "grid-column",
        "grid-gap",
        "grid-row",
        "grid-template",
        "grid-template-areas",
        "grid-template-columns",
        "grid-template-rows",
        "height",
        "inset",
        "justify-content",
        "justify-items",
        "justify-self",
        "left",
        "letter-spacing",
        "line-height",
        "list-style",
        "list-style-type",
        "margin",
        "margin-bottom",
        "margin-left",
        "margin-right",
        "margin-top",
        "max-height",
        "max-width",
        "min-height",
        "min-width",
        "object-fit",
        "opacity",
        "order",
        "outline",
        "overflow",
        "overflow-x",
        "overflow-y",
        "padding",
        "padding-bottom",
        "padding-left",
        "padding-right",
        "padding-top",
        "place-content",
        "place-items",
        "place-self",
        "pointer-events",
        "position",
        "resize",
        "right",
        "rotate",
        "row-gap",
        "scale",
        "scroll-behavior",
        "text-align",
        "text-decoration",
        "text-indent",
        "text-overflow",
        "text-shadow",
        "text-transform",
        "top",
        "transform",
        "transition",
        "translate",
        "user-select",
        "vertical-align",
        "visibility",
        "white-space",
        "width",
        "word-break",
        "word-spacing",
        "word-wrap",
        "writing-mode",
        "z-index",
    };
    std::copy(std::cbegin(T), std::cend(T), std::back_inserter(types));
}
